### ISSUE TITLE
chocolate-doom and crispy-doom conflict on hexen.cfg.5

### ISSUE THREAD

**Issue by jengelh** [fabiangreffrath/crispy-doom#1036]
### Background

Version of Crispy Doom: 5.12.0; chocolate-doom 3.0.1

Operating System and version: Linux x86_64 6.2.8

### Bug description

Observed behavior: When `make install` is called from the crispy-doom source tree, it installs a file called hexen.cfg.5 (and heretic.cfg.5, etc.)

```
$ make install
...
 /usr/bin/install -c -m 644 default.cfg.5 crispy-doom.cfg.5 heretic.cfg.5 crispy-heretic.cfg.5 hexen.cfg.5 crispy-hexen.cfg.5 '/home/abuild/rpmbuild/BUILDROOT/crispy-doom-5.12.0-6.1.x86_64/usr/share/man/man5'
```

The corresponding output from chocolate-doom is

```
...
 /usr/bin/install -c -m 644 default.cfg.5 chocolate-doom.cfg.5 heretic.cfg.5 chocolate-heretic.cfg.5 hexen.cfg.5 chocolate-hexen.cfg.5 strife.cfg.5 chocolate-strife.cfg.5 '/home/abuild/rpmbuild/BUILDROOT/chocolate-doom-3.0.1-56.1.x86_64/usr/share/man/man5'
```

The result is that the two engines overwrite manpages from one another. In the context of distribution package production, this is detected early on and the distro-level build/install logic is telling me that only chocolate-doom _or_ crispy-doom can be installed.

A rename of hexen.cfg, heretic.cfg.5, strife.cfg.5 seems in order to resolve stepping on chocolate-doom's files.
Yeah, the _content_ of the file may be the same (I doubt it was touched since the fork from chocolate-doom), but for distro packaging, let's find an easy way out.

Expected behavior:

rename hexen.cfg.5 to crispy-doom-hexen.cfg.5? (It's not quite clear why there is chocolate-hexen.cfg.5 and hexen.cfg.5)

**Comment by fabiangreffrath** [comment]
This has been reported before: https://github.com/fabiangreffrath/crispy-doom/issues/936

> rename hexen.cfg.5 to crispy-doom-hexen.cfg.5? (It's not quite clear why there is chocolate-hexen.cfg.5 and hexen.cfg.5)

The point is that the `hexen.cfg.5` manpage is the format documentation for the file called `hexen.cfg`. There is no file called `crispy-doom-hexen.cfg.5`. The reason why there are two files in the first place is that `hexen.cfg` contains all the configure flags that were already present in the original DOS version (which is why it's the same for both Chocolate and Crispy) and the port-specific configure flags are saved in `chocolate-hexen.cfg` and `crispy-hexen.cfg`, respectively.

**Comment by fabiangreffrath** [comment]
This is an issue that must be solved on the packaging side. This is, for example, who I do it in the Debian package:
https://salsa.debian.org/debian/crispy-doom/-/blob/master/debian/rules#L17
