### ISSUE TITLE
Features from Strawberry Doom?

### ISSUE THREAD

**Issue by Danfun64** [fabiangreffrath/crispy-doom#106]
D'oh! accidentally pressed enter in the description. Please don't make any comments until I make a proper description...

edit: Several years ago, GhostlyDeath started work on Strawberry Doom, which would have been a limit removing Chocolate based port (basically the role that Crispy fulfills now). Strawberry Dooms goal would have been to add features like splitscreen, and apparently implemented "in-game multiplayer scoreboard which also shows player health and armor information, enhanced and color contextualized automap (which was also copied into ReMooD), primitive bots with primitive navigation for any level, and deathmatch team support."

Of course, what wasn't alpha/beta in Strawberry Doom has long been obsoleted by a newer Chocolate Doom base, but if was possible without affecting demo compatibility, I'd appreciate it if some of these features could be implemented (especially split-screen and the bots)

**Comment by Danfun64** [comment]
Fixed the description :P

**Comment by fabiangreffrath** [comment]
Hm, you'll have to agree that "be more like Strawberry Doom" is a bit vague as a feature request. ;) Especially since, as you stated, the code bases have diverged over years, and it might be impossible to simply port over some of the more interesting features (note that I have already ported over the "flipped levels" feature).

Furthermore, split-screen multiplayer requires severe changes to all parts of the engine ranging from the input system to the rendering stack. I am not sure if it would be even possible for me to implement this in my limited time and judging from the Strawberry changelog, it also has been started there but never really finished. In the end, it might be ambitious goals like this that could never get reached and might eventually kill one-man projects like Strawberry or Crispy.

I am tempted to mark this request as "wontfix", but actually I would "fix" it if someone filed a pull request. ;)

**Comment by fabiangreffrath** [comment]
I don't think it is helpful to keep this open. Please come back with more concrete feature requests.
