### ISSUE TITLE
Claim ownership of the flatpak

### ISSUE THREAD

**Issue by ghost** [fabiangreffrath/crispy-doom#1061]
There's a [flatpak of crispy](https://flathub.org/apps/io.github.fabiangreffrath.Doom) published on flathub. I suggest that @fabiangreffrath claims ownership of the package for the below reasons:
- Once verified, the app will receive a "verified" badge to prove that the package is published by the author (example image below)
- It could be given more care (update wise). The flatpak is currently at v5.12. A huge selling point of flatpaks is to provide the latest version regardless of your system dependencies, and there is no reason for it to be stuck in an old version.

I've found [quick instructions on the flathub website](https://github.com/flathub/flathub/wiki/App-Submission#someone-else-has-put-my-app-on-flathubwhat-do-i-do) on how to claim ownership.

![image](https://user-images.githubusercontent.com/120708663/236156485-39c7723f-4324-4d56-96e4-0be8bf53cc81.png)

**Comment by rfomin** [comment]
But then we need to build the flatpack ourselves. This is probably a good idea, although I'm not a Linux user.

**Comment by fabiangreffrath** [comment]
I don't use flatpak, I don't care for it and I don't want to maintain it.

**Comment by kiwphi** [comment]
A part of me was anticipating this reaction, but it came off a bit more "raw" than expected :laughing:

**Comment by fabiangreffrath** [comment]
Sorry, I didn't mean to sound rude. I was just thinking "how do I say that I don't care for this" other than "I don't care for this". 😉

**Comment by kiwphi** [comment]
Allow drop one last argument before we close this.
I'm all for traditional packaging and i tend to lean towards this side of things. I don't use flatpak either (or any other one of those newer trends such as appimages, snaps etc...). But flatpak has its place somewhere. Most non-technical persons using Linux will probably be either on Ubuntu or Mint, and they'll be stuck playing the old version. Flatpak offers a good solution to this.
Also, it doesn't seem a pain to maintain like the traditional package...

**Comment by fabiangreffrath** [comment]
> But flatpak has its place somewhere.

Sure, but I expect the people who care about it to maintain it themselves. DEB packages also have their place somewhere, but I expect people who care for these packages to maintain the `debian/` directory themselves. That being said, I *do* actively care for Debian packages, and nevertheless I don't maintain a `debian/` directory as a part of this port's sources.

> edit: after a quick glance, seems like it's just a single manifest that we'll prepare the first time, then after this the only thing to change will be the version number (after each release), since there are no changes in dependencies 99% of the time

Let's say I'd accept PRs doing this janitor stuff for me. 😉

**Comment by mikeday0** [comment]
I haven't messed too much with flatpaks, but couldn't an interested party (say, @kiwphi :wink:) contribute directly to https://github.com/flathub/io.github.fabiangreffrath.Doom?

**Comment by kiwphi** [comment]
I'll work on it just after i finish setting up the website. Could you (@fabiangreffrath) at least just claim ownership so that you can have write access to the [repo](https://github.com/flathub/io.github.fabiangreffrath.Doom) instead of a third party. This will also get the package as verified.
It's also irking me because I'm linking to it from the website. Not to sound corporate, but it would be "more correct" to link to an "verified" package.

**Comment by fabiangreffrath** [comment]
Since there is already a manifest in the flathub repo, I have written them an email and claimed ownership of it. Let's see where this leads us.

**Comment by fabiangreffrath** [comment]
Should be done now.

**Comment by kiwphi** [comment]
alright, i'll work on it and see what i can pull off. i'll keep you posted

**Comment by davidarnold** [comment]
Hi there :wave: 

I'm the creator / maintainer of the Flatpak.  It's kind of weird that no one attempted to contact me about this, but the reason why the Flatpak is behind in version is due to an annoying issue with the Freedesktop SDK version 22.08 breaking SDL2_mixer and SDL2_net dependency, which prevented the build from completing.  I opened an upstream bug nine months ago, but since then, there has only been a resolution on the SDL2_mixer problem.  SDL2_net still breaks the build.

True, this is not strictly a blocker as we could continue to release on 21.08, but I was (incorrectly) expecting a timely resolution since I assumed that this would be a big problem for many other Flatpak games.  There is also an alternative approach where we bypass the Freedesktop SDK and build SDL2_net ourselves directly from source.  This is the [approach that the Chocolate Doom Flatpak used](https://github.com/flathub/org.chocolate_doom.ChocolateDoom/commit/7d8834ee9f4d3145498b79ff4f344e802f8d756e).

At any rate, since there seems to be so much angst about the Flatpak being behind and I don't want to keep Crispy stuck on 21.08, I'll probably use the Chocolate Doom hack and get a 6.0 release out the door today.

Note for @Calinou: updating to 6.0 is more than bumping the tag in the file.  We need to expose the new Strife apps in the Flatpak configuration to fully support the new release.  If there are any new features in 6.0 that I've missed, please let me know!

Thanks, all :v:

**Comment by fabiangreffrath** [comment]
> This issue can probably be closed. The Flatpak itself needs to be updated to 6.0, but this should be tracked separately.

Well, let's do it then.

> If there are any new features in 6.0 that I've missed, please let me know!

I think the re-introduction of Crispy Strife is the most important change from a packaging point of view.
