### ISSUE TITLE
`numiwadlumps` needs re-evaluation, else embedded DEHACKED lumps are skipped

### ISSUE THREAD

**Issue by kitchen-ace** [fabiangreffrath/crispy-doom#1101]
Here's an odd one: This wad contains a sprite named SPIDA0D0, the first & fourth frame of the spiderdemon with rotation set to 0 so it's the same from all angles. The sprite itself loads fine, but causes the included DEHACKED lump to not be loaded, even with the `-dehlump` switch. All the DEH does is start you with 5 bullets instead of 50, and change the mapname of the first map.
```
W_Init: Init WADfiles.
 adding /home/user/Games/doom/doom2.wad
 merging spidbug.wad !
  loaded 0 DEHACKED lumps from PWAD files.
```
Loading the dehacked separately with `-deh` works fine. Deleting the SPIDA0D0 lump also makes the DEHACKED from the wad load fine.

The wad & deh also load properly in Woof & DSDA-Doom. The deh doesn't load in Chocolate with `-dehlump -merge` but I don't know if that counts as accurate vanilla behaviour or not.

[spidbug.zip](https://github.com/fabiangreffrath/crispy-doom/files/12756353/spidbug.zip)

**Comment by kitchen-ace** [comment]
Wad is derived from one the user in this DW thread sent me:
https://www.doomworld.com/forum/topic/140304-solved-crispy-doom-is-not-loading-the-deh-file-in-my-wad-anymore/?tab=comments#comment-2709024

Oddly enough, that wad had a lot more sprites and other content, and it was the H0 and I0 frames of the spiderdemon that were causing problems, and renaming those fixed the wad.

**Comment by fabiangreffrath** [comment]
Not that odd, actually. The culprit is the `numiwadlumps` check in `D_DoomMain()`.

Once the engine loads the IWAD, its value is set to `numiwadlumps = numlumps`.

https://github.com/fabiangreffrath/crispy-doom/blob/e69e50c9cd6dccc245bbe8252dae3ebac013b876/src/doom/d_main.c#L1666

For my copy of DOOM2.wad that'd be 2919. Then the PWAD is loaded and the `numlumps` value is increased by 4 (i.e. S_START, SPIDA0D0, S_END, DEHACKED).

https://github.com/fabiangreffrath/crispy-doom/blob/e69e50c9cd6dccc245bbe8252dae3ebac013b876/src/w_wad.c#L209

But then the lumps are merged in `DoMerge()` and the `numlumps` value decreases to 2913, i.e. below the inital value that initialized `numiwadlumps`. 

https://github.com/fabiangreffrath/crispy-doom/blob/e69e50c9cd6dccc245bbe8252dae3ebac013b876/src/w_merge.c#L553

Thus, the `for (i = numiwadlumps; i < numlumps; ++i)` loop will never execute.

https://github.com/fabiangreffrath/crispy-doom/blob/e69e50c9cd6dccc245bbe8252dae3ebac013b876/src/doom/d_main.c#L2023

**Comment by kitchen-ace** [comment]
Huh, neat, I was totally unaware of most of that.

I guess this is a Chocolate Doom problem then?

**Comment by fabiangreffrath** [comment]
> I guess this is a Chocolate Doom problem then?

Yes, probably. I'll see if I can fix it there.
