### ISSUE TITLE
Heretic/Hexen: possible to save a game when no game running, leads to segfault

### ISSUE THREAD

**Issue by kitchen-ace** [fabiangreffrath/crispy-doom#1137]
In Heretic and Hexen you can attempt save the game from the menu when no game is active. Doing this when there is no game results in a segfault, doing it while watching internal demos acts like it works but saves nothing. This is vanilla behaviour but no reason it should be kept here.

Doom and Strife prevent you from saving if you're not playing.

Also a problem in international-heretic @JNechaevsky

**Comment by JNechaevsky** [comment]
Very nice find, thank you! It is possible to fix, like in Doom, it's just a question of `usergame` boolean. But before, let's first let's confirm one of two possible approaches of handling this case, i.e. how we will warn and prevent user from entering Sage Game menu:

1. Print centered message. This behavior is traditional to Doom, but not very for Heretic's menu. This will require extra key press to get rid of this message, additional `typeofask` case and handling of "closing / getting back to menu".
2. Print message on top. Just like when trying to select other than first episode in shareware version. This is slightly simpler, but because of small oversight in original Raven code, such message will hang until menu is changed. Technically, this is because of `messageTics` are reducing only while `GS_LEVEL` gamestate is active. It is possible to fix, and this will fix enterely problems of "forever" messages in game menu like "Messages ON/OFF" and "Gamma-Correction" ones.

Personally, I'd prefer to go with 2nd approach but would like to hear @fabiangreffrath and @mikeday0 recommendations first, as this is Crispy Heretic and additional Crispy-style improvement in game menu were made.

**Comment by fabiangreffrath** [comment]
The most simple solution would be to just not open the save menu and play the "oof!" sound instead.

**Comment by fabiangreffrath** [comment]
How about this?

```patch
--- a/src/heretic/mn_menu.c
+++ b/src/heretic/mn_menu.c
@@ -1260,6 +1260,11 @@ static boolean SCSaveGame(int option)
 {
     char *ptr;
 
+    if (!usergame)
+    {
+        return false;
+    }
+
     if (!FileMenuKeySteal)
     {
         int x, y;
```

**Comment by JNechaevsky** [comment]
Ah, even simpler! User still can get into the Save Game menu, but can't perform saving. This is also handles case on trying to save game while demo playback. Probably it's and ideal approach for keeping traditional Raven style of menu handling, let's go this way then, I'll prepare a RP.
