### ISSUE TITLE
[Suggestion] Smooth screen flash for pickups and damage feedback

### ISSUE THREAD

**Issue by JS299990** [fabiangreffrath/crispy-doom#1206]
ZDoom/GZDoom make it so the screen flash fades in and out whenever you pick up stuff or take damage. It's a lot easier on the eyes.

Example:

https://github.com/user-attachments/assets/d881b563-7740-4612-9b76-bfe1ecf142fe

Would be possible to add a feature like this for Crispy Doom as an accessibility option for people who are sensitivity to flashing lights?

**Comment by fabiangreffrath** [comment]
Not sure what you see, but I still see the screen flashing up for a split second. Do you really say this makes a difference for people sensitive to flashing lights? 

Also, I think that the red pain flashes should be an instant reaction to the player receiving harm. I'd be very surprised by the red tint building up while my player is dying. 😉

**Comment by JNechaevsky** [comment]
Actually, optional smooth palette fading is possible in TrueColor and it looks gorgeous. For the reference, [this function](https://github.com/JNechaevsky/international-doom/blob/main/src/doom/st_bar.c#L994). In short: instead of switching palette indexes, a pane alpha is changed according amount of player's `damagecount` or `bonuscount`. Berserk is a "special guest" unfortunately, because of it's timing implementation in original code.

The result:

<details>

https://github.com/user-attachments/assets/9c07dc95-8764-4c6a-b64a-8ae4ceecbe2b

</details>

Despite of very simple implementation, it's a TrueColor-only feature, I haven't investigated how this could be possible in paletted render and can't suggest it for Crispy. Also, this most likely will put a cross on possible support of custom palette tinting effects for TrueColor...

**Comment by JS299990** [comment]
> Not sure what you see, but I still see the screen flashing up for a split second. Do you really say this makes a difference for people sensitive to flashing lights?
> 
> Also, I think that the red pain flashes should be an instant reaction to the player receiving harm. I'd be very surprised by the red tint building up while my player is dying. 😉

I completely agreed with you and to be honest it's not a big deal. I'm very sensitive to flashing lights but also it's not like Doom is making my eyes water all the time. I don't see the effect being instantaneous as an issue, It's when the effect stacks that it really messes ups my vision and it takes me a second to look a the screen again.

**Comment by JS299990** [comment]
> Actually, optional smooth palette fading is possible in TrueColor and it looks gorgeous. For the reference, [this function](https://github.com/JNechaevsky/international-doom/blob/main/src/doom/st_bar.c#L994). In short: instead of switching palette indexes, a pane alpha is changed according amount of player's `damagecount` or `bonuscount`. Berserk is a "special guest" unfortunately, because of it's timing implementation in original code.
> 
> The result:
> 
> Despite of very simple implementation, it's a TrueColor-only feature, I haven't investigated how this could be possible in paletted render and can't suggest it for Crispy. Also, this most likely will put a cross on possible support of custom palette tinting effects for TrueColor...

That looks really cool. 
I understand now that it wouldn't be beneficial to add this to Crispy. Thank you for looking into this.
