### ISSUE TITLE
kill *all* the slime trails

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/crispy-doom#129]
There should be a way to eliminate all the slime trails. Not that I'd had an idea, yet, but there _must_ be a way...

**Comment by fabiangreffrath** [comment]
Iterate through all the subsectors and check that all the segs and nodes that surround it form a closed circle. Any ideas how to implement this? Anybody?

**Comment by AnotherLife** [comment]
This would need a node rebuild, with extended nodes, right? But then demo compatibility suffers.

**Comment by AXDOOMER** [comment]
Add a node builder in the engine that uses fixed-points and that builds a set of nodes used only for the rendering, so the nodes used for the collision detection stay the same. The only data you would need from your new set of nodes would be the segs and their vertices, because they are the ones that cause this bug when there are not on an integer coordinate. 

Slime trails are caused by open subsectors. You could merge vertices that are 1 unit close to each other together if they are along the same line. Of course, you'd still keep the unfixed map data for demo compatibility.

**Comment by fabiangreffrath** [comment]
I don't think it would be necessary to rebuild the nodes at all. Also, I already maintain two separate sets of vertex coordinates for game logic and rendering.

My idea is to detect open subsectors and close them by merging two vertices by changing their rendering coordinate to match each other.

**Comment by AnotherLife** [comment]
Is there a pwad that suffers from some classic cases of slime trails,  so it can be used for testing?

Some '94 era map that can make for a good test case?

**Comment by fabiangreffrath** [comment]
I'd say E1M1 is the prime example here:
https://doomwiki.org/wiki/E1M1:_Hangar_(Doom)#Slime_trails

**Comment by fabiangreffrath** [comment]
The critical point is to know which segs surround a given subsector!

Sure, each `struct subsector_t` has a `numlines` and a `firstline` element, but these are really just the segs for which the subsector in question is on the `frontsector` side. In fact, subsectors may share segs with adjacent subsectors and these segs only appear once in the list for the first subsector.

What is needed here is either a `frontsubsector`/`backsubsector` pair of fields in `struct seg_t` or a full list of surrounding segs (including those shared with other subsectors) in `struct subsector_t`. But how do we get to either of this?

**Comment by fabiangreffrath** [comment]
Closing orphaned issues and pull requests.
