### ISSUE TITLE
Extend to other resolutions

### ISSUE THREAD

**Issue by No-Kelvin** [fabiangreffrath/crispy-doom#13]
I'm not talking about field of view nor screen scaling (as it happens in chocolate-doom), just support for more resolutions. User should have the option to keep the game's aspect ratio (resulting in black bars on the sides) or just stretch it to the whole screen.

**Comment by Danfun64** [comment]
If this and #8 are considered wontfix, why are they still open?

**Comment by fabiangreffrath** [comment]
I was expecting more requests to even higher display resolutions and wanted to keep this bug visible in order to answer these requests early on.

**Comment by Zodomaniac** [comment]
Is it possible to implement 16x10 widescreen resolutions (640x400, 960x600, 1280x800 etc.) in Windowed mode?

**Comment by fabiangreffrath** [comment]
It would be a major pain in the ass to implement proper rendering in widescreen modes, because that changes the field of view, which is hard-coded to be 320:200 in a lot of places in the code.

Don't mix this up with DR's "widescreen" mode. It merely renders the part above the status bar and puts some HUD elements on it.

**Comment by Zodomaniac** [comment]
Well, if 640x480 and other 4:3 resolutions in windowed mode are possible,
why aren't 640x400 and other 16x10 possible?

2016-03-09 19:00 GMT+03:00 Fabian Greffrath <notifications@github.com>:

**Comment by fabiangreffrath** [comment]
640x400 is a possible resolution if you disable "Aspect Ratio Correction" in the Video settings of crispy-doom-setup. It is even the framebuffer's native resolution.

However, Crispy Doom inherits Choco's rendering algorithm which stretches each pixel by factor 1.2 vertically before it is rendered to screen (if Aspect Ratio Correction is enabled, that is). This is all based on look-up tables and thus fixed to the original resolution, which I merely extended to 640x400 for Crispy.

Things will get more flexible with the switch to SDL2, but I am still unsure if Crispy will ever get native widescreen resolution support.

**Comment by fabiangreffrath** [comment]
Well, because 1600x1200 isn't an integer multiple of 640x400, whereas 1280x800 is simply (640x400)*2.

You can only have integer multiples of 640x400 or -- with Aspect Ratio Correction enabled -- 640x480. In the latter case each pixel is stretched vertically by factor 1.2. These are all our choices with the software-based rendering of the SDL1.2 code base. There are no resolutions available in between.

**Comment by Zodomaniac** [comment]
Thus, as I see, 1600x1000 (not 1200, you've misread it ;)) and 960x600 window resolutions are selectable in the menu but impossible because they are not multiples of 640x400. Maybe remove them from the menu then?

Congrats on releasing Crispy 3.3 btw ;) was looking forward to it, thanx a lot!

**Comment by fabiangreffrath** [comment]
No, wait, I was mistaken. There are some intermediate resolutions which get some interpolated pixels inserted in horizontal or vertical (or both) directions.

It is about two years ago that I adopted the software scaling routines for Crispy Doom. Somehow my brain must have retrospectively simplified matters as some kind of self-protection mechanism. ;)

All the resolutions that are shown in the Video settings menu are really available, though the offer is currently quite limited. With SDL2 the rendering area will be scaled to whatever dimensions your screen or window has and it will get stretched into the right aspect ratio on the fly.

**Comment by Zodomaniac** [comment]
Then I think I have to report an issue because in windowed mode 960x600 resolution falls back to 640x400 and 1600x1000 falls back to 1280x800.

**Comment by fabiangreffrath** [comment]
Hm, yes, you are right. If Aspect Ratio Correction is disabled, then only integer multiples of the original resolution are available. I should fix this in the setup program, thank you!

**Comment by Zodomaniac** [comment]
Downloaded the Mar 25 daily build, looks like without 'fix aspect ratio' the 960x600 and 1600x1000 resolutions are just removed. Could you add them back and make'em work?

**Comment by fabiangreffrath** [comment]
These two resolutions have never been available in Crispy Doom, because they aren't integer multiples of the native 640x400 resolution, so I removed them from the list. Selected intermediate resolutions are only available in the "fix aspect ratio" mode.

However, the two resolutions are natively available in Choco, because they are 320x200 times 3 or 5, respectively.

**Comment by fabiangreffrath** [comment]
I think this is fixed with the switch to SDL2 in Crispy Doom 5.0 and onward.
