### ISSUE TITLE
Crispy Heretic?

### ISSUE THREAD

**Issue by aynrandjuggalo1** [fabiangreffrath/crispy-doom#132]
I'm interested in Crispy Heretic, so I tried editing the makefile (in Ubuntu 16.10) to create a crispy-heretic executable. It failed. I assume it's not possible to compile a Crispy Heretic executable in the code's current state?

I would be possibly interested in maintaining the Crispy Heretic code, but I am certainly not an expert programmer. Computer Science is my minor in college. I have a beginner-to-intermediate understanding of C, but a much, much firmer grasp of Java (I won an award in High School, and the department chair of my small college personally wrote me a letter upon completing CSC102) -- and I guess I know Visual Basic too. I have no experience with the Doom source code, or with making WADs. Would maintaining Crispy Heretic be a trivial enough job that a novice like me could do it? I assume it would involve taking the latest code from Chocolate Heretic and connecting it up with the Crispy code, which seems like something a novice could handle.

If maintaining Crispy Heretic is NOT something a novice could handle, but still not too difficult for an experienced programmer, I'm petitioning you guys to revive it. My reasoning for why Heretic deserves the Crispy treatment is as follows: Crispy Strife seems obsolete now that the Veteran Edition exists, so there's no need to maintain it. Hexen (which I've actually never played) seems quite different from Doom. Heretic, on the other hand, is very, very close to the core Doom experience. If maintaining Crispy Heretic is not hard, it would be one more part of the classic Doom experience that Crispy Doom can emulate and enhance. Plus, some of the WADs in Maximum Doom require Heretic, and when I complete my own project of an easy-to-parse text file containing enough information to launch every level of Maximum Doom, you want Crispy Doom to be compatible, don't you? DON'T YOU?

Personally, if Crispy Heretic existed, I would make the switch from Chocolate Doom to Crispy Doom as my source port of choice, but that's just my own weird internal reasoning. Let me know what you think of all this.

**Comment by fabiangreffrath** [comment]
I have disabled building of the three non-Doom games from the Choco sources, because I am not at all interested in them, they were left behind in terms of development since the Crispy 1.0 release and I was merely carrying them along as dead weight.

However, their source code is always kept in sync with Choco and all the improvements that are achieved there. It is just that they aren't built anymore!

To get them back to compiling, you'll have to have a look at e.g. these commits and revert the relevant parts:
https://github.com/fabiangreffrath/crispy-doom/commit/70b7eb436ece39b8f66afd2862a53cd8a8cbe3df
https://github.com/fabiangreffrath/crispy-doom/commit/e56e1732d1b8bcd0f0ceb108cb28de12b3e0a648

You may want to try this in a separate branch and file a pull request once you got them (or only Heretic) back into a state that's worth maintaining. There is really nothing speaking against Crispy Heretic, it is just that I don't wanto to take over maintenance for it. But you seem motivated enough. ;)

**Comment by fabiangreffrath** [comment]
I have seen that @JNechaevsky has recently extended the Heretic part of Russian Doom quite exhausively, so maybe he would like to step in as the maintainer for Crispy Heretic? Just asking... ;)

**Comment by JNechaevsky** [comment]
@fabiangreffrath, with my pleasure. :) But before starting we need to discuss technical and some non-technical aspects. I will send you e-mail with my thoughts very soon.

**Comment by fabiangreffrath** [comment]
This is now tracked in detail in https://github.com/fabiangreffrath/crispy-doom/issues/240
