### ISSUE TITLE
Loading NERVE.WAD with the original (non-BFG) DOOM2 IWAD causes a crash in the main menu

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [fabiangreffrath/crispy-doom#135]
Error: Bad music number 1983888883
The crash occurs at the moment when the title music stops playing and the demo playback should start.
This bug is present in Crispy Doom v3.x and didn't appear in v2.3.

**Comment by fabiangreffrath** [comment]
Thank you for finding this! Actually, this is a pretty severe bug and I wonder why it doesn't show in earlier versions.

When `NERVE.WAD` is loaded, `gamemission` is set to `pack_nerve` and the music to play for each map is taken from array `int nmus[]` which has 9 elements. The first demo in `DOOM2.WAD` plays MAP11 (IIRC), so we read past the boundaries of that array.

It will be properly fixed in the next commit, thanks!
