### ISSUE TITLE
In case of lag in game startup (e.g. when the system is busy) music begins to play before the level/menu loads

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#151]
Showing my Infested Outpost soundtrack-synchronized demo to friends I noticed that on the first launch or with massive processes running in the background the soundtrack kicks in before the game starts which is rather awkward.
I deem it would be better to start playing music when the actual game begins and not before the game even starts up.

**Comment by fabiangreffrath** [comment]
Sorry for not getting back to you on this earlier.

The underlying cause for this issue is quite apparent: `S_Start()` is called pretty early in `P_SetupLevel()`, way before the rest of the map (i.e. vertices, lines, sectors, blockmap, etc.) is loaded. While the latter may take several seconds, the music is already playing.

However, I don't see anything bad in this, quite the contrary: The music acts as a progress indicator of some kind. As long as the map loads, you are confronted with a black screen, but at least the music plays, so you can be confident that the game didn't hang or crash. Imagine the other way round: You wait for a rather huge map to load for several seconds in front of a black screen *in utter silence*. This would feel really foul and time would feel like passing in slow motion.

So, although I understand this this behaviour somehow plays against music synchronisation tricks, it is nevertheless rather intentional to start the music before the map has finished loading and thus I am not going to change it, sorry.

**Comment by fabiangreffrath** [comment]
@Zodomaniac Is this still an issue or may we close it? I think map startup was exceptionally slow back when  I still used the original BSP blockmap generator. But now that I have reverted back to MBF's implementation some releases ago, I think map loading time shouldn't be an issue anymore, right?

**Comment by Zodomaniac** [comment]
I think we can close it, yes :)
