### ISSUE TITLE
Issues with loading savegames from the menu when playing ioutpost.wad after the commits 4305 and 4306 (in daily builds of Feb 19 and 20, 2017)

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#153]
I updated the daily build to Feb 19 version, and now If I'm playing Infested Outpost, the attempt to load a savegame from any WAD from the Load menu results in this window popping up:
![error window](https://cloud.githubusercontent.com/assets/15119473/23117178/87a8f3f6-f75f-11e6-8d9c-c2ceed1712b1.png)
Here's the archive with my savegames, including IOutpost, Batman Doom and just Doom 2.
[save_issues.zip.txt](https://github.com/fabiangreffrath/crispy-doom/files/787203/save_issues.zip.txt)
Remove the .txt from file extension, there's some issue with this machine that's not mine that Github won't accept ZIP-files from it and I'm forced to add .txt.
It's worth noting that when I'm in Batman Doom or Doom 2, loading from the menu works properly (resulting in loading the game or asking whether to continue restoring it from the current WAD or not), but if Infested Outpost is loaded, then instead of these reactions the error window shown above pops up.

P.S. Loading the Infested Outpost savegames with BAT-file works well.

**Comment by fabiangreffrath** [comment]
Oh damn!
Does the IOutpost level have a brain spitter?

So, do I understand you correctly: If you have ioutpost.wad loaded, then *any* attempt to load a savegame will fail with this error message even before the warning/question appears and if you have not loaded ioutpost.wad then it all works as expected?

**Comment by Zodomaniac** [comment]
> If you have ioutpost.wad loaded, then any attempt to load a savegame will fail with this error message even before the warning/question appears and if you have not loaded ioutpost.wad then it all works as expected?

Yes, exactly!
I don't know for sure if the WAD has a brain spitter because it has a Dehacked-modified monster: the Cyberdemon has modified attacks, maybe he is a brain spitter initially...

**Comment by Zodomaniac** [comment]
You should be able to reproduce the same bug in today's snapshot, as it was built from the same commit as the yesterday's snapshot.

**Comment by fabiangreffrath** [comment]
What was the latest snapshot you had before this (i.e. when was the last time this worked)?

**Comment by Zodomaniac** [comment]
> What was the latest snapshot you had before this (i.e. when was the last time this worked)?
I think in the Feb 18 snapshot it still worked, but I deleted the zip, I cannot check now.

**Comment by fabiangreffrath** [comment]
I have just pushed a fix to GIT, I hope that helps. Would you please reopen if it doesn't?

**Comment by Zodomaniac** [comment]
Unfortunately it didn't work. But I've investigated a bit further and discovered that Crispy errors out on savegame loading attempt only when the game is in progress, just loading the WAD with -merge (and no savegame load command) and then loading a game from the menu does work.
Here's a BAT-file that loads the WAD only but no savegame.
[ioutpost_not_loading_savegame.bat.txt](https://github.com/fabiangreffrath/crispy-doom/files/789442/ioutpost_not_loading_savegame.bat.txt)
.

**Comment by fabiangreffrath** [comment]
> Please add me as a collaborator to this repo ;)

With great pleasure!

I think I found the bug in the precache code, this could explain why it occured only if a map was already loaded.

**Comment by Zodomaniac** [comment]
Thanks for the add, as they used to say at MySpace :)
Will test the tomorrow's snapshot :)

**Comment by Zodomaniac** [comment]
Hell yeah, you've fixed it, tanks a ton...no, tanks are tens or even hundreds of tons! :)

**Comment by fabiangreffrath** [comment]
Phew, what a relief, thanks for testing!

Let me add some rationale to this:

Doom expects all its flat lumps between the `F_START`/`F_END` markers, it even calculates the `numflats` variable as the number of lumps within that range. Actual flat pictures are saved as an index counting from `0` that is `firstflat` (i.e. `F_START + 1`) up to `numflats`. Now, in order to support for animated flats, Doom allocates the `flattranslations[]` array with `numflats` elements, which takes a flat index and returns the next index in the animation sequence. Note that at this point, all indices are considered relative to `firstflat` and are thus expected to be in the range between `0` and `numflats`.

Problems arise when there a duplicate flat lumps or generally flat lumps outside the `F_START`/`F_END` range in a PWAD. The `R_FlatNumForName()` function merely calls `W_CheckNumForName()` and asserts that its return value is `> -1`. It does not check, however, that the returned lump number is *really* within the "flats" range. Now, the flat's index is calculated by subtracting the value of `firstflat` from the lump number and -- depending on the lump's position in the merged WAD data -- this index may be way out of range, e.g. `< 0` or `> numflats`. Calculating the next flat in the animation sequence by passing this index to the `flattranslations[]` array finally leads to the errors and crashes that you experienced.

Boom fixed this by restricting the lumps returned by `R_FlatNumForName()` to be within the "flats" range. Formerly, I did the same as well, but this restriction isn't compatible with PWADs that need to be loaded by one of the `-nwtmerge`, `-af` or `-aa` parameters. So, I needed to add some special-casing. 

Then, I decided to not like this anymore, because it's non-Vanilla and requires some hickhack that I'd like to get rid of. But now, what about the strictly non-Vanilla PWADs with their flats lumps out of the "flats" range that have been supported before? Well, I added some run-time sanity checks for them and hopefully, things will work out as expected in the future.
