### ISSUE TITLE
When moving the mouse in the menu in multiplayer, the view also moves, both sideways and up'n'down

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#155]
I know you made the view not move in singleplayer along either axis while moving the mouse in the menu, so I suppose you will prefer to make it behave the same way in multiplayer as well ;)

**Comment by fabiangreffrath** [comment]
I know about this, but fixing it is not as easy as it sounds. In singleplayer mode, the game is literally paused when the menu is active, i.e. no further tics are processed. In multiplayer mode, though, the engine needs to continue on processing tics, because one player opening the menus must not have any effect on the other players in the game. Thus, the mouse events are still passed through to the game and interpreted as moving the view. I'll have to look into it...

**Comment by Zodomaniac** [comment]
Thanks :)
Is the player in-game also prevented from rotation (I mean sprites seen by other players) when he's moving the mouse in the menu?

**Comment by fabiangreffrath** [comment]
It's a real tic action, so the player is actually rotating.

**Comment by Zodomaniac** [comment]
I should have asked this in the first place...diverging the view from player rotation is not good. Feel free to revert this change :)

**Comment by fabiangreffrath** [comment]
No no, it's all fine. Horizontal mouse movement in the menus rotates the player in multiplayer games and this is exactly what is seen in the scene rendered behind the menu. So, there is no need to worry about this, IMHO. Or are you referring to anything else?

**Comment by Zodomaniac** [comment]
I wrote the previous comment before testing, so it's all fine :) Nice fix  :)
