### ISSUE TITLE
Player respawn on Fire as well as Use

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#161]
For about 20 years it's common in FPS games to respawn/restart level after death by clicking the "fire" button, the newer players like me can get a bit confused after death in Doom DM that they should hit Use to respawn.

**Comment by fabiangreffrath** [comment]
Hm, this is very specific to Doom and changing it would thus feel, uhm well, un-Doomy. ;)

Please, would you do me a favor and move this request over to the Choco tracker asking for a key binding for the "respawn" action? If it gets accepted there, I'll merge it here.

**Comment by JNechaevsky** [comment]
Please wait. I have a feeling that it will not be accepted, since it's non-vanilla.

Maybe it might be a good idea to don't change from `Use` to `Fire`, but make `Fire` also available for resurrection?

**Comment by Zodomaniac** [comment]
> Maybe it might be a good idea to don't change from Use to Fire, but make Fire also available for resurrection?

That's what I said in the issue title: Player respawn on Fire as well as Use ;)

**Comment by JNechaevsky** [comment]
Oops, sorry! My bad.

**Comment by fabiangreffrath** [comment]
Guys, I cannot simply add Fire as another key for player respawn.

Back when I implemented respawning from the latest savegame, I bound this to the Fire key and people got mad (it's now bound to Run+Use). Why? Because when you die in battle, you usually die with your finger on the trigger. So, it is very much possible that you unintentionally press the fire button in the moment of your death and then you instantly respawn -- although this was neither intended nor expected.

If you really want a different key for player respawn, it should be possible to re-assign it. Globally adding another key is out of the question for the reasons I stated above. And if it should be possible to reassign this key, it should not be a Crispy-specific feature, but get implemented one step upstream in Choco.

**Comment by Zodomaniac** [comment]
I should think of it a bit before posting an upstream issue. Is it possible to bind the respawn key to different buttons in singleplayer/coop and in DM/DM2.0?

**Comment by fabiangreffrath** [comment]
No, button assignment is the same for all game modes. And respawning from savegames is only possible in singleplayer games.

BTW, reporting upstream isn't worse than reporting here. Fraggle won't rip your head off. ;)

**Comment by Zodomaniac** [comment]
@fabiangreffrath 
Fraggle rejected this initiative, so what is your opinion on implementing this in Crispy?

**Comment by fabiangreffrath** [comment]
Yep, I have seen that and I am inclined to agree. But if you really insist on it, I can implement that, no problem.

**Comment by Zodomaniac** [comment]
>But if you really insist on it, I can implement that, no problem.

Very nice of you, looking forward for the configurable or additional binding ;)

**Comment by Zodomaniac** [comment]
@fabiangreffrath 
>now that you owe me a favor, how about the release notes? ;)

Sure, you can rely on me :)

**Comment by Zodomaniac** [comment]
@fabiangreffrath 
>Back when I implemented respawning from the latest savegame, I bound this to the Fire key and people got mad (it's now bound to Run+Use).
If that latest savegame is on the previous level, Run+Use respawns you at the start of the level you died on, as well as just Use. Is that intentional?

**Comment by fabiangreffrath** [comment]
Yes, this is intended. Respawning from a savegame should never push you back into a previous level.
