### ISSUE TITLE
set proper sound source for "oof!" sounds emitted when trying to open a locked door

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#172]
As was promised in https://github.com/JNechaevsky/russian-doom/commit/c29af1aa30cf1658a9e56d145b0cc617a5223827, here it is.

For now, pressing any door that require a key makes "oof!" sound from `NULL` source:
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/p_doors.c#L224

This is okay for single player game, but in multiplayer sounds weird: https://youtu.be/K0njTlIhXHs
All players are hearing this "off!" despite of distance from each other. 

Suggestion: `player->mo` must be declared as activator/sound source in EV_DoLockedDoor?

_Suggestion №57_

**Comment by fabiangreffrath** [comment]
In general and by pure logic I agree with you. But, you know, people are very sensitive about sounds (most requests to revert a fix so far were because of sound changes). And I want things to work exactly the same in single- and multiplayer games (except for sheer game breakers). Also, it might be useful in a multiplayer game to know "by instinct" that you co-player is unsuccessfully trying to open a door at the moment.

**Comment by JNechaevsky** [comment]
Ahh, got it, got it. Well, sounds more than reasonable, so let's just leave it "as is". Maybe it will be even better to stop any further sound research/suggestions at all, or at least do it only in case of serious problems or bugs.

**Comment by Zodomaniac** [comment]
In co-op this can even be explained by the marines activating the radio when trying to open a locked door, to report in to teammates. But for deathmatch gamemodes, why not fix it, as all the playerz are enemies and would rather not give away their positions?

**Comment by AXDOOMER** [comment]
In deathmatch, you always have the keys for every door, so it never happens.
