### ISSUE TITLE
Save and restore gametic to preserve Revenant's homing missiles 

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#174]
Well, actually this may be considered as a half-bug, but I don't like the word "bug".

Here's the situation: a friend of mine noted me a very interesting case with Revenant's homing missiles. If I got everything right, despite of preserving the code of "tracer" in saved games _(str->tracer)_, there is still a change to homing missiles will loose homing after loading a saved game. It happens randomly and I believe this is because of `if (gametic & 3)` in `A_Tracer`. I.e., even after loading saved game, `gametic`'s random acts it's role. 

Here's how it looks: https://youtu.be/86j3OEXoF3I
Note, that sometimes missiles remain to be homing, sometimes not after loading.

Suggested solution: Hmm... Maybe `dest` must also be stored in saved games? Or some tweaks/flags with `if (gametic & 3)`? All my code experiments gives me nothing.

_Suggestion №59_

**Comment by fabiangreffrath** [comment]
Thank you very much! It is incredible that I have never heard of this bug before, but it's not only Crispy that is affected. There is an excellent analysis over at the Doomsday tracker, which suggests that saving and restoring the gametic value might fix the issue:
https://tracker.dengine.net/issues/1868

**Comment by fabiangreffrath** [comment]
I see that saving and restoring the gametic variable is the obvious solution to fix singleplayer games. However, I am hesitating to apply this to Crispy Doom, because I am pretty sure that this will instantly destroy saving and loading multiplayer games.

**Comment by JNechaevsky** [comment]
Meanwhile, let me explain some of my thoughts and attempts of fixing this issue. I have tried two approaches, both gives me nothing, guess because of I'm do something wrong in the code, so please consider them only as ideas.

1. `dest` should be preserved in saved games. Saved games already have information about tracer, right? And even after they are loosing target after loading game, they still have a smoking tracer. So maybe it is necessary to directly point them, whom to fly? Logic must be something like this:
- The game and all it's data loaded
- A_SkelMissile invokes
 - If it have dest-ination (written in saved game), let it fly to this destination. If it does not have (which must means that this is not homing missile), let it just fly forward.

2. Use `byte missilehastarget;` for A_SkelMissile by this example:

```
void A_Tracer (mobj_t* actor)
{
    angle_t	exact;
    fixed_t	dist;
    fixed_t	slope;
    mobj_t*	dest;
    mobj_t*	th;
    byte missilehastarget;
		
    if ((missilehastarget!= 1) && (gametic & 3))
	return;
    missilehastarget = 1;
    
    // spawn a puff of smoke behind the rocket		
    P_SpawnPuff (actor->x, actor->y, actor->z);
```
- But something not enough here. Must be `missilehastarget` also preserved in saved game?

**Comment by fabiangreffrath** [comment]
- `dest` is a local variable to `A_Tracer()` and it is set to `actor->tracer` which in turn is preserved in savegames -- that's the reason why it sometimes still works after restoring.
- You cannot request the value of `missilehastarget` before you have set it. It's uninitialized. This won't work.

Are you really sure that missiles still emit smoking tracers even if they lose target during a save/restore cycle? I am sure they don't and that would also be contradictory to how I understood this issue so far.

A Revenant's rocket being homing or not depends on the *gametic* when it was fired. The `A_Tracer()` function is called only every second tick, so if it has been called once on an odd or even tic, it will be so over the whole lifetime of the rocket. The even/odd-ness of the tic is checked at the beginning of the function and it is either left early before homing the target or not.

The problem is that now the homing feature depends on the gametic when the game was *restored*, because that's the tic when all of the `A_Tracer()` functions for all of the rockets are called -- as if they were just spawned at the same time.

Anyway, the distinction of  `actor->tracer` being set or not may turn out helpful here, thanks for that!

**Comment by JNechaevsky** [comment]
> Are you really sure that missiles still emit smoking tracers even if they lose target during a save/restore cycle? I am sure they don't and that would also be contradictory to how I understood this issue so far.

Doh, yes, I was wrong. I have checked - after loading game, if missiles are loosing their target, they are loosing smoke too.

**Comment by JNechaevsky** [comment]
@fabiangreffrath, @bradharding, colleagues, I have another awful thing regarding smoking tracers.

It it possible to make them **loose target** by pressing `Pause` key. Sometimes it removes target after first pausing/unpausing, sometimes it is necessary to spam this key. All three projects are affected, as well as Vanilla.
😱

**Comment by fabiangreffrath** [comment]
This is because `gametic` keeps on ticking under the hood. The only sensible thing that a port not caring about demo-compatibility could do is replace `gametic` with `leveltime` in `A_Tracer()`.

**Comment by JNechaevsky** [comment]
Thanks for explanation!
Hmmm. This looks likes another good spot for `if (singleplayer)`, I believe it's a one and only safest solution here.

**Comment by fabiangreffrath** [comment]
I don't think there is a clean way to fix this in a demo and netgame (if at all?) compatible manner without fiddling with the engine's "heart beat". So, it seems like this issue is directly depending on https://github.com/fabiangreffrath/crispy-doom/issues/92 .

**Comment by JNechaevsky** [comment]
Fabian, despite of you have said your decisive Word, I still would like to insert my last note.
You have made an amazing thing called `singleplayer`, which you are trying to use only in case of critical necessity, but for my needs I find it completely amazing. 

It's looking safe, it is safe actually, so having a code:

```
    if(singleplayer)
    {
        if (leveltime & 3)
        return;
    }
    else
    {
        if (gametic & 3)
        return;
    }
```

can be a perfect solution. There is also might be Killough's `(gametic-levelstarttic)` fix, but that's another story. Yes, it's for single player only, but AFAIK many things and fixed was made only for single player. So is it really necessary to care about network game in this case? Crispy in not only multiplayer port, and maybe you will change your mind?

And in any way, as usual - at your discretion.

**Comment by fabiangreffrath** [comment]
@JNechaevsky Yes, I know that the solution you propose will work.

The point is that I don't want different code paths at run-time anymore. I already permit some decisions during map start-up or between maps in order to support as many maps as possible or to act as logical as possible. But I don't want the engine to behave differently in-game whether I play a singleplayer game, a network game or whether I record or play back a demo. If there is a bug and there is a fix for it, I aim for a solution that does not need to distinguish between the different game modes. I have already jumped through quite some burning loops for this.

There will be some issues for which there is no clean solution or for which the most obvious solution is not safe enough. But then, the most natural behavior is to fall back to how Vanilla Doom did it. And for the moment I am afraid this is one of these issues.

**Comment by JNechaevsky** [comment]
Ah, now I got it completely. This is most hardest path of all, but it also one and only proper in the Philosophy of compatibility. Thank you for explanation!

**Comment by fabiangreffrath** [comment]
Well, I have already fixed this for demo recording and playback in https://github.com/fabiangreffrath/crispy-doom/commit/b9ccc9d9696648ee6b02983b385ab4e557fd5e11 and I am not sure if it is possible to fix the other issue (i.e. tracer getting added or lost when `gametic` and `leveltime`get out-of-sync) without losing network compatibility with Choco.

**Comment by fabiangreffrath** [comment]
I am closing some old issues that I consider irrelevant by now. Feel free to reopen with a comment if you disagree.
