### ISSUE TITLE
Give the Doomguy the permanent STFGOD0 in case of invulnerability (at least)

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#183]
The weapon pickup smile and baring teeth (when holding fire) sprites don't have glowing eyes in Invulnerability.

**Comment by fabiangreffrath** [comment]
I know, this is because there aren't any graphics for that in the game. Would you really prefer not changing the face over changing the face to "human" eyes for a while? 

I've always seen it that grinning and gritting teeth are emotional acts that reveal the human nature of Doomguy and thus hide his god-like eyes for a while. Something like this...

**Comment by Zodomaniac** [comment]
> Would you really prefer not changing the face over changing the face to "human" eyes for a while?

Yes, I would, because the godface is so static (unlike STFIST01 that has options STFIST00 and STFIST02) that to me it would be logicat that it doesn't show any emotions.

In fact, the perfect option would be adding additional graphics like @JNechaevsky did in Russian Doom 2.2, but you don't want to bundle any WADs with Crispy AFAIK.
![doom_god_emotions](https://cloud.githubusercontent.com/assets/15119473/24957313/fa3bed5e-1f93-11e7-9563-a5055b20cc76.png)

**Comment by JNechaevsky** [comment]
I have to explain some thoughts about golden eyes while rampage/grinning.

I will never stop thanking @bradharding for teaching me how to implement this and @fabiangreffrath for his amazing face hysteresis fix, which is making this completely proper looking, but there are few colossal problems with this lovely feature.

1. It will require and additional pwad with graphics, which is not acceptable for Crispy.
2. In therms of code, the safest approach to do this - double face's array. It does not break original face code and numeration, but require some face "placeholders" for pain and etc. states, even despite of they will never appear (because we have a "god mode state in god mode state"). This is how it is done in my project, but another possible approach - is to completely rewrite face's code, what is seems to be the most horrible nightmare.
3. It is unsafe for compatibility. I.e., in case of PWAD contains new HUD faces, it will not have faces for god mode rampage/grinning. This will require addition hack or check of containing new faces, but Chocolate's combination of `W_CheckNumForName` + `DEH_AddStringReplacement` does not seems to can handle this.

So yeah, for the project which is aimed to play only vanilla series, this is okay and fine.
But for the projects which is aimed to support global and heavy modifications and TCs - this is a big headache.

**Comment by Zodomaniac** [comment]
Then IMO let's agree at giving Doomguy the static STFGOD0 in invulnerability.
BTW, it was done this way by @JNechaevsky in Russian Doom 2.1.

**Comment by fabiangreffrath** [comment]
First, skipping the rampage and grinning faces in god mode should be rather easy. I will just have to make sure that the `priority` value is not changed in these two states in `ST_updateFaceWidget()` if god mode is enabled.

Adding the ability to show these graphics provided by PWADs is a different (and more complicated) topic.

**Comment by fabiangreffrath** [comment]
@JNechaevsky How are the two additional patch lumps called?

**Comment by JNechaevsky** [comment]
@fabiangreffrath, it is whole array of faces actually, not just a two faces. I have named them as STF***G, because this whole array is for **G**od mode. But here's these two:

Grin: STFEVL0G
Rampage: STFKIL0G

**Comment by JNechaevsky** [comment]
P.S. I've also was thinking about making optional "blooded god mode face", but was not lucky, 
This seems to be because of even despite of whole additional array, game strictly uses STFGOD0G for common face while god mode (looking & pain), but can use different faces for rampage/grin with blood (which is looking strange to have a bloody face in grin/rampage, while common faces is not bloody). 

In fact, I have rejected this idea, it both technical and non-canonical reasons.

And to be 100% honest, the idea and code of still face while god mode comes from Doom Retro, where it's using and to this day.

**Comment by fabiangreffrath** [comment]
> Grin: STFEVL0G
> Rampage: STFKIL0G

Thanks! Do you know any other ports that support grin and rampage sprites for god mode? If yes, how are these sprites called there?

**Comment by JNechaevsky** [comment]
AFAIK, there are no ports, with this feature, and looks likes, there are even no mods/TCs with this. :Ъ

**Comment by JNechaevsky** [comment]
Gentlemen, excuse me for this necro-posting, but take a look at this mugshot sequence, which you are possibly haven't seen before:
![](https://tcrf.net/images/6/6c/DOOMGBA_JaguarMugshot.gif)

According to this [source](https://tcrf.net/Doom_(Game_Boy_Advance)), Doomguy's head explosion initially comes from Atari version. What a mess, eh?
