### ISSUE TITLE
Suggestion for the distance of the sprite rendering algorithm

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#186]
Also may be considered as "suggestion for MAXVISSPRITES".

Current algorithm of maximum sprite displaying and rendering works absolutely well, but I think it can be improved a bit. I can not fully understand `R_NewVisSprite` stuff, but it seems to have rendering logic is based on some kind of blocky stuff (sprite map numbers + visplanes?)

Like this: https://youtu.be/2wV2I58m7to

How this logic can be improved: maybe it will be better to draw nearest for the player sprites, while not to draw far ones, that is out of MAXVISSPRITES limits?

Why it is necessary: I believe there are only two reasons.

1. This seems to be more logical.
2. This must be a good salvation for maps that uses a lots of sprite graphics, decorations and monster fireballs. I'm not very familiar with pwads of any kind, but only our favorite nuts.wad comes to mind.

From another hand, this sounds more like an interesting technical research, rather than critical necessary for the gameplay.

Map from the video: http://jnechaevsky.users.sourceforge.net/files/maxstimpacks.zip

_Suggestion №64_

**Comment by fabiangreffrath** [comment]
Hi Julian,

yes, this is a well-known problem (try e.g. to no-clip through NUTS.WAD) and unfortunately I don't know an easy workaround for this. The culprit is in this code:

https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/r_things.c#L852

This engine iterates through the BSP tree and calls `R_Subsector()` for each visible subsector. This, in turn, calls `R_AddSprites()` which adds all the sprites in the corresponding sector to the vissprites array. The engine stops doing this if either all sectors have been processed or the MAXVISSPRITES limit is reached. Then it sorts the vissprites array by distance from the player.

Now, the problem is that neither the sectors are ordered in any way relative to the player's position and that the filling of the vissprites array may stop before a sector close to the player is even reached.

The solution would be something like this: Instead of calling `R_AddSprites()` for each sector that the BSP tree "sees", add the sectors to an array. Then, after the BSP tree has been processed, sort that array by the player's distance to the sector and finally call `R_AddSprites()` for each sector in that sorted list. This is really fiddling with the innards of the rendering core...

**Comment by JNechaevsky** [comment]
Fabian, as usual, thank you very much for explanation! I think now I can understand this process, at least logically.

Yeah.. Reworking this code does not seems to worth it's effort. Maybe this is even good, because mappers are have to care about visible sprite limits, and maybe even better to hide this idea into the drawer for "better times".

Thinking about your solution, yes, I have to agree that this is a proper way, that must not add any additional CPU usage for each gaming frame, or even maybe will act as some rendering optimization, hard to imagine, it's pure technical moment. :)

Thinking a little bit more, I was planning to offer something like this procedure:

1. First of all, engine must calculate distance from the player to any visible sprites in player's FOV.
2. Now BSP tree must act it's role for proper clipping and hiding parts of the sprites behind walls. If I understand this correctly, without BSP tree stuff it will be possible to see all sprites through the walls, which we differently don't want.
3. Depending on the distance + MAXVISSPRITE limit, engine must decide what to draw and what to not. Only nearest and closest should be appeared.


But again, this sounds easy/logical only on the words, and I have feeling that something is missing in my logic.

**Comment by fabiangreffrath** [comment]
> Instead of calling R_AddSprites() for each sector that the BSP tree "sees", add the sectors to an array. Then, after the BSP tree has been processed, sort that array by the player's distance to the sector and finally call R_AddSprites() for each sector in that sorted list.

I just hacked up something like this, it didn't help! The problem with both the sample map that you provided and nuts.wad is that all map things are in one single sector (well, two in the case of nuts.wad), so sorting the sectors by player distance doesn't make a difference.

What *would* help, though, is sorting all visible map things by player distance. But this would have to be kept in sync with the player position and I think that this can only hardly be accomplished at run-time. :/


[crispy-sortsectors.patch.txt](https://github.com/fabiangreffrath/crispy-doom/files/926007/crispy-sortsectors.patch.txt)
