### ISSUE TITLE
Support ExM0 maps, e.g. as in No End In Sight megawad

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#192]
This megawad
https://www.doomworld.com/idgames/levels/doom/Ports/megawads/neis
contains E1M0 and E4M0 bonus maps that IMO should be supported and be available to IDCLEV to.

**Comment by fabiangreffrath** [comment]
Too bad they didn't call the one E1M10, that would have been supported due to the XBOX IWAD.

Could you please check with Vanilla if these are actually reachable by IDCLEV? Are they even reachable by specifying the `-warp` parameter?

Apart from this, I don't think we need to support every insane extra secret level that the next best Megawad introduces -- I am not saying that NEIS is just the next best Megawad, but the next one may be. ;) IWADs are somehow different, though.

**Comment by fabiangreffrath** [comment]
Ah, they specify in the TXT file that the extra maps are meant solely for ZDoom and Eternity...

**Comment by fabiangreffrath** [comment]
Do you know which map contains the secret exit to E1M0? Maybe I could pimp the E1M10 implementation a bit to also support this case.

**Comment by Zodomaniac** [comment]
No map has exits to E1M0.
https://onemandoom.blogspot.ru/2017/03/no-end-in-sight-neiswad.html
It also includes two super-secret levels only playable in Zternity ports, one which must be warped to (E1M0) and one which can be reached by an additional secret exit in E4M6 (E4M0).

BTW, there's no clear explanation of the reason why these levels are only playable in Zodom and Eternity, maybe the only reason is that other ports just don't support zero-th maps? If so, why not add the support for zero-th maps to Crispy?

**Comment by fabiangreffrath** [comment]
> there's no clear explanation of the reason why these levels are only playable in Zodom and Eternity

They have MAPINFO support.

> If so, why not add the support for zero-th maps to Crispy?

You do not simply add support for 0th maps. Look at all the crap I had to add just to properly support E1M10 in the XBOX IWAD...

**Comment by fabiangreffrath** [comment]
![one-does-not-simply2](https://cloud.githubusercontent.com/assets/6449237/25609297/e725cc54-2f1e-11e7-8753-0b7202fd4b42.jpg)

**Comment by fabiangreffrath** [comment]
So, what _would_ be needed in order to support a PWAD with **E1M0**?

1) First, we would have to get rid of (or relax) this check:

https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/g_game.c#L2163

2) Then, we would have to deal with the music missing for this map:

https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/s_sound.c#L798

3) Then, we would have to deal with the map title missing for this map:

https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/hu_stuff.c#L53

Once these are fixed, the map would start and be playable, but I am not sure what would happen when leaving the map. We would need a map name patch for the intermission screen, par times and coordinates for the blood splat (or disable it). The main problem is that all these result in array underflows, since indices are generally 0 for E1M1 and thus -1 for E1M0.

Hypothetical question (maybe even not so): What should happen if the first PWAD appears with E1M-1 or MAP-1?

**Comment by Zodomaniac** [comment]
I see you're taking steps towards ExM0 support, that's great!
Wiil it be possible to IDCLEVx0 to these maps? :D

**Comment by fabiangreffrath** [comment]
I won't make any promises! ;)

No, seriously, I was just trying to see what would be necessary to support these maps and fixed the obvious crashers on the way. The main issue, though, is still the direct dereferencing of the `mapnames[]` array in (3). So, in the end, I am still very reluctant to relax the check in (1), because this will open a whole can of worms for all kinds of subsequent bugs (i.e. the consequence would be to support *all* kinds of episode and map numbers, not just E1M0 and E4M0, but this rises the question what to do with e.g. E-1M100 or E99M-11 and the like).

I have gone through all this before for supporting of MAP33 and E1M10, but these were **IWADs**, and I really don't see why the NEIS authors needed to introduce another set of maps that require special support.

**Comment by Zodomaniac** [comment]
>this will open a whole can of worms for all kinds of subsequent bugs

Can of worms for bugs :) I really love this pun :1st_place_medal:
