### ISSUE TITLE
Can't load a saved game when a netgame demo is playing

### ISSUE THREAD

**Issue by AXDOOMER** [fabiangreffrath/crispy-doom#198]
If you load Memento Mori where the in-game demos are all multiplayer demos, Crispy Doom won't allow the player to load a saved game while one of them is playing. The same would occur if you'd play a multiplayer demo using `-playdemo`. This is a vanilla Doom bug. 

To fix it, search for `QLOADNET` and `LOADNET` in `m_menu.c`. Each are in a conditional block that checks if the game is a `netgame`. You have to add `&& !demoplayback`. If you search for `NEWGAME`, you'll see that the condition of its block is `netgame && !demoplayback`, which means that the developers were probably aware that loading saved games during multiplayer demo playback caused a problem.

The problem in question is that after loading the saved game, the game still remains in "netgame" mode. It can be noticed by trying to enter cheat codes or by looking at the background color of the status bar face. To fix it, you must go in `g_game.c` and find the function `G_DoLoadGame `, where you must disable the netgame by simply doing `netgame = false;`.

**Comment by fabiangreffrath** [comment]
Hm, how does PrBoom+ handle this?

**Comment by fabiangreffrath** [comment]
Could you please file a PR with minimal changes and in-line comments everything you changed? So I could point my finger to you if anything breaks. ;)

Also, please note the shading of the menu entries that needs adjustments, too.

**Comment by AXDOOMER** [comment]
Sorry, I don't really have the time to do a PR. I didn't have time in the last 26 days and it will probably never get on my TODO list.

**Comment by JNechaevsky** [comment]
Allow me please, then.

First of all, PrBoom+ test (latest 2.5.1.4-win32):

- MM is loaded though `prboom-plus.exe -file MM.WAD`.
- Starting new single player game and saving it.
- Now, ending the game and wait for demo starts to playing.
- First (multiplayer) demo starts.
- Trying to load game by `F3` - loading is allowed.
- After loading, I've got my saved game in single player mode. Everything seems to be okay.

Now about the code. Everything is very simple, and here's how it should be done in Crispy's code:

https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/m_menu.c#L985
```
    if (netgame && !demoplayback) // <----- added && !demoplayback
    {
	M_StartMessage(DEH_String(QLOADNET),NULL,false);
	return;
    }
```

https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/m_menu.c#L838
```
    if (netgame && !demoplayback) // <----- added && !demoplayback
    {
	M_StartMessage(DEH_String(LOADNET),NULL,false);
	return;
    }
```

https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/g_game.c#L1843
```
void G_DoLoadGame (void) 
{ 
	 
    netgame = false; // <----- added
    gameaction = ga_nothing; 
	 
    save_stream = fopen(savename, "rb");
```

Finally, after compiling and checking by the same way as in PrBoom+, everything works okay and behaves as in PrBoom+. I believe this is safe, since the game itself is not allowing to load multiplayer save games for multiplayer mode.

I can make a PR if necessary.

**Comment by fabiangreffrath** [comment]
> I believe this is safe, since the game itself is not allowing to load multiplayer save games for multiplayer mode.

This was my main concern with the original approach, that adding `netgame = false` to `G_DoLoadGame()` would entirely kill the ability to load multiplayer games. But, this has never been posible anyway, right?

> I can make a PR if necessary.

Yes, please do so (with comments). Thank you!

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/crispy-doom/commit/0d20ff0282ee706e7ae68c208aef390d728f5672

Merged, thanks!
