### ISSUE TITLE
Remove "screen shot" message from screenshots

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#203]
When taking multiple screenshots, the "Screen Shot" message appears in the second and the following screenshots.
Sometimes being forced to shoot one screen in a few seconds, to avoid this message, is annoying,
also the "Screen Shot" notification kills the in-game message (chat, weapon pickup message etc.) if one is being displayed which is undesired if you wanted to make multiple screenshots while the message is still on the screen.
Clean screenshot doesn't catch the message string at all and it doesn't portray the weapon either.
So IMO an extra setting that would let the player catch in-game messages in a series of screenshots by suppressing the "Screen Shot" notification is useful.
It can be categorized as a Visual setting: "Screen shot notification: On/Off" (On by default, as it's the way Vanilla/Choco behaves).

**Comment by fabiangreffrath** [comment]
Only over my dead body will this deserve its own switch in the menu! ;)

I am afraid there isn't much I can do about the screenshot message replacing previous in-game messages, because this is just how Doom's messaging system works. What I could probably do, though, is remove the screenshot message from the actual screenshot, because when you are looking at a screenshot it should be pretty obvious that it's a screenshot. ;)

**Comment by JNechaevsky** [comment]
I can suggest something like:
```
	    V_ScreenShot("DOOM%04i.%s"); // [crispy] increase screenshot filename limit
	    if (!devparm)
            players[consoleplayer].message = DEH_String("screen shot");
	    gameaction = ga_nothing; 
	    break; 
```

Remembering our previous talks, I think `-devparm` can be useful for some changes like this (also for disabling wiping, quick saving/loading and exiting without prompt and so on). It's for developing, not for casual, err, pure playing, and maybe it is safe to make some changes in development parameter. Maybe.

**Comment by Zodomaniac** [comment]
@fabiangreffrath 
> What I could probably do, though, is remove the screenshot message from the actual screenshot, because when you are looking at a screenshot it should be pretty obvious that it's a screenshot. ;)

Yes, that would be great!

**Comment by fabiangreffrath** [comment]
> `-devparm`

Na, I'd rather not overload this command line parameters with random functionality. Instead, I'd prefer to find a reasonable compromise.

**Comment by fabiangreffrath** [comment]
Phew, this isn't as straightforward as I initially thought. Once `player->message` points to a string, this string is mangled into the `w_message` widget in the next tic and `player->message` is reset, so there is no easy way to check from the outside whether the message currently shown is "screen shot" or not.

Anyway, everything is impossible until it is not!

**Comment by AnotherLife** [comment]
Can't you instantly clear/timeout existing messages from the screen and then force a new frame to be redrawn without advancing the tic? Then screenshot that and show a message about it.

**Comment by fabiangreffrath** [comment]
This is exactly how the "clean screenshot" feature currently works. The trick is now to restrict this only to the message line and only if the current message is the "screen shot" one...

**Comment by Zodomaniac** [comment]
This appears to have been partially handled in https://github.com/fabiangreffrath/crispy-doom/commit/49cd7c8d9ad0add3d2a54b727dc43c2181e19fb6 as Clean screenshot has the weapon now if HUD is drawn.
Do you plan any commits regarding "sync with Doom Retro"? If not, then "complete and order-keeping WAD/DEH list" in extended savegames and removing DOS references in quit game dialogs will do for 4.2 release IMHO))

**Comment by fabiangreffrath** [comment]
> This appears to have been partially handled in  49cd7c8  as Clean screenshot has the weapon now if HUD is drawn.

Na, not really, this is something different. Although I have to admit that this fix got my attention while trying to implement the "no screenshot messages on screenshots" issue (what a beast!).

> Do you plan any commits regarding "sync with Doom Retro"? 

This was just to keep the first extra state and mapthing that we added at the same position, because Brad recently changed the order.

> If not, then "complete and order-keeping WAD/DEH list" in extended savegames and removing DOS references in quit game dialogs will do for 4.2 release IMHO))

Honestly, I am not really convinced by the former. As I already stated, I don't like it in PrBoom+ and I don't consider it the engine's responsibility to remind the player to keep his stuff together -- it just shouldn't crash. 

And regarding the latter, it's just a cosmetic fix, though I appreciate the obsession that you seem to have for it. ;)

Whatever, even with two more fixes this isn't going to be Crispy 4.2 yet. I have more or less established a 3 months cycle depending on development activity and I'd like to keep it that way unless something really severe shows up.

**Comment by Zodomaniac** [comment]
Isn't the recently eliminated crash https://github.com/fabiangreffrath/crispy-doom/issues/207 and also other fixes you've done enough for a version bump? I'd love to have libsamplerated smooth sound and PNG screenshots with these fixes))

**Comment by AnotherLife** [comment]
Fabian can you just squeeze out a current executable and attach it here? And dlls if they are updated, I guess?

**Comment by fabiangreffrath** [comment]
Unofficial intermin release!

[crispy-doom_git8cd2e3d5.zip](https://github.com/fabiangreffrath/crispy-doom/files/1111741/crispy-doom_git8cd2e3d5.zip)

**Comment by Zodomaniac** [comment]
Tanks a lot Fabian, and also AnotherLife for your support! )))
