### ISSUE TITLE
The bug of Black Ops with ioutpost.wad: the fountains and pistol viewsprite replace each other depending on the WAD loading order

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#216]
If I launch the game with 
`start crispy-doom -merge ioutpost.wad blackops.wad`
the water fountains are replaced by pistols:
![doom0017](https://user-images.githubusercontent.com/15119473/29936718-e3e13f02-8e8b-11e7-9dd8-d2d32391bb64.png)
And if I launch the game with
`start crispy-doom -merge blackops.wad ioutpost.wad`
and fire the pistol, it turns into a fountain in the top left corner of the screen, lol
![doom0004](https://user-images.githubusercontent.com/15119473/29936979-b9af94ee-8e8c-11e7-8725-b35f4fbd8762.png)

**Comment by fabiangreffrath** [comment]
I am pretty sure that there isn't much we can do about that, as both SMOOTHED and BLACK OPS add dehacked patches and sprite changes that are incompatible to the ones that IOUTPOST itself
introduces. This is to the extent that it even crashes Choco when both PWADs are loaded simultaneously, as we have fixed in #207.
