### ISSUE TITLE
SMOOTHED breaks the special attacks of the Cyberdemon in ioutpost.wad

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#217]
As you can see on the screenshots attached to https://github.com/fabiangreffrath/crispy-doom/issues/216 the Cyberdemon at ioutpost.wad fires Revenant's missiles as well as standard rockets, and with SMOOTHED.WAD loaded Cyberdemon doesn't shoot Revenant missiles anymore.

**Comment by fabiangreffrath** [comment]
I am pretty sure that there isn't much we can do about that, as both SMOOTHED and BLACK OPS add dehacked patches and sprite changes that are incompatible to the ones that IOUTPOST itself
introduces. This is to the extent that it even crashes Choco when both PWADs are loaded simultaneously, as we have fixed in #207.
