### ISSUE TITLE
Chainsaw start buzz can still be interrupted by the 'oof' sound of falling or pressing against the wall, even when Playing sounds in full length is on

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#228]
Noticed that at the very start of Doom 2: grabbed the chainsaw, jumped off the ledge, and here it is.

**Comment by fabiangreffrath** [comment]
You are absolutely right, but unfortunately I don't see a way to prevent this.

Let me explain: Each player has two objects connected to it that can emit sounds. One (`player->mo`) is his "mouth", i.e. where the "oof" comes from, and the second one (`player->so`) is the gun nozzle, i.e. where the firing sounds come from. In general, if a sound is emitted by one source, it interrupts the sound that is currently played from that source, but it doesn't affect the other source.

Now, in the case of the chainsaw, I want to avoid that its constant buzz is interrupted by "oof" sounds e.g. when you walk down a steep stair. In order to achieve that, I moved the buzz sounds to the `player->so` object. However, I also want to avoid that the first of the constant buzz sounds interrupts the chainsaw start-up noise, so I had to leave the latter connected to the `player->mo` object. This, in turn, means that any other sound emitted by the `player->mo` object will interrupt the chainsaw start-up sound. And as I stated above, this includes the player's "oof" sounds.

Thus, I don't see a way out of this situation, apart from introducing a third sound source (which I won't).
