### ISSUE TITLE
add optional brightmaps

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/crispy-doom#246]
I'd like to add brightmaps to textures and sprites. Their implementation should be resource saving and non-intrusive and not block the transition to full truecolor rendering in the future.

References are the implementation in DR
https://github.com/bradharding/doomretro/blob/master/src/r_data.c#L97

and Russian Doom
https://github.com/JNechaevsky/russian-doom/blob/master/src/doom/r_data.c#L994

**Comment by JNechaevsky** [comment]
Permalinks to the testing maps:

- [bmaps-d1.wad](http://jnechaevsky.users.sourceforge.net/files/brightmaps/bmaps-d1.wad)
- [bmaps-d2.wad](http://jnechaevsky.users.sourceforge.net/files/brightmaps/bmaps-d2.wad)
- [bmaps-tnt.wad](http://jnechaevsky.users.sourceforge.net/files/brightmaps/bmaps-tnt.wad)

They should be loaded depending of game the game (Doom 1, 2 or TNT), because different games have/using slightly different names and textures.

I've also added few sprites, glowing sectors and upper/lower segmented walls, so everything can be tested pretty well. Hope this helps!

**Comment by JNechaevsky** [comment]
Updated testing maps of D1 and D2 with few floor textures, mentioned in https://github.com/fabiangreffrath/crispy-doom/commit/cc30f47509dfca3291709f485369702ebaadf755#commitcomment-26535599. They are placed in the right side of the maps.
