### ISSUE TITLE
Demo timer is displayed on top of the FPS counter

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#266]
Demo timer is displayed on top of the FPS counter. I think it makes sense to move the FPS counter one line down and align it to the right side of the screen if the demo timer is active so that the timer and the counter don't interfere with each other.

**Comment by fabiangreffrath** [comment]
Yes, I agree the positioning is a bit unfortunate here. However, I cannot simply move the FPS counter one line down, because then it would clash with the X coordinate in the automap. I guess it will have to be "one or the other".

But since this is a design question, does @JNechaevsky have another idea?

**Comment by fabiangreffrath** [comment]
There is a `if (plr->powers[pw_showfps])` check in `HU_Drawer()` that draws the FPS counter widget. I could move the demo timer widget into the `else` part and be done with it.

**Comment by Zodomaniac** [comment]
>I could move the demo timer widget into the else part and be done with it.

What will this yield exactly? Disable the FPS indicator if demo timer is active?

**Comment by fabiangreffrath** [comment]
The other way round: The demo counter will be displayed until you enter SHOWFPS (at which point you have probably already lost the interest in a speed run), then it will show the FPS widget.

**Comment by Zodomaniac** [comment]
OK) And the demo timer should re-appear if SHOWFPS/IDRATE is toggled or when the next level starts.

**Comment by JNechaevsky** [comment]
Fabian, you can do something like this:
```
if (IDRATE)
{
    // Move record timer one text line lower by Y coords
}
else
{
    // Standard Y coords of record timer
}
```
But for aesthetic reason, both record timer and FPS counter should be aligned by right part of the screen.

**Comment by fabiangreffrath** [comment]
We also have IDMYPOS to consider...

**Comment by JNechaevsky** [comment]
Oh, I see. Give me few hours to think please, I think I can offer something, but right now my head is about to explode after second day of new job.

**Comment by JNechaevsky** [comment]
Okay, let's think. What is most valuable while demo recording? Timer. Next, we have a map coords thah should not have placement relocation, so they should have a static position. And finally, we have a FPS counter, that's probably will not be enabled in normal demo record, so I think suggested placement is:

1. Demo timer
2. Map coords
3. FPS counter _(can be placed right below demo timer, if map coords are disabled)_

Again, for aesthetical reason, FPS counter can be done like: `FPS %s`, to accord apperance of map coords.

Probably, this will be most safest approach because you need to take care only about FPS counter placement.

**Comment by fabiangreffrath** [comment]
Two remarks:

(1) Currently, the demo timer is drawn in the top-right corner of the *window*, not *screen*. This makes a difference for smaller displaysizes as it means that I don't have to redraw the bezel during each tic if the timer is enabled [this would become a lot easier if the timer was a widget registered in HU_Init()]. Thus, the demo timer does not always collide with the FPS counter, but depending on the value of displaysize, may also collide with the X or Y coordinate widget.

An alternative would be to drop the status bar ammo widget font once again and implement the demo timer in the same widget as the FPS counter and have its actual value depend on SHOWFPS being active or not and demo recording/playback being active or not - with SHOWFPS taking precedence, because that has to be enabled manually.

(2) Right aligning the FPS counter and coordinate widgets would mean (a) to re-calculate the X position of each widget during each tic to account for the varying width of the printed numbers and (b) to have the "X", "Y", "A" and "FPS" markers shift back and forth on the horizontal axis because of that. I'd rather leave the markers' position stable and have the numbers left-aligned.

**Comment by fabiangreffrath** [comment]
That being said, I am currently in a situation in which two features stand in each other's way - literally. This is a symptom of featuritis and indicates a direction, in which I never actually wanted to drive my port... :/

Probably time to finally stop adding more features once and for good...

**Comment by JNechaevsky** [comment]
Hmmm. Maybe something like this...

```
if (crispy_demotimer >= 1)
{
    place FPS row beneath IDMYPOS's "A:"
}
```

**Comment by Zodomaniac** [comment]
@fabiangreffrath Is @JNechaevsky 's option valid?

**Comment by fabiangreffrath** [comment]
I am currently resistant to see the demo timer as a widget that should arrange with the other group of widgets (fps counter, idmypos) that we currently have. Not only because of its different font, I see it as a separate widget that is simply drawn on top of everything else.[*]

Anyway, I'll give this proposal a try. ;)

[*]  Sorry for the many "widgets" in these sentences.

**Comment by fabiangreffrath** [comment]
Guys, is this a **real** problem that anyone has ever actually encountered or is this merely another theoretical "it could be an issue if one would do _this_ and _that_ at the same time" kind of issue?

**Comment by Zodomaniac** [comment]
@fabiangreffrath I can agree that it makes no sense to display FPS when recording a demo, as demo recording has little to no effect on the performance. If you consider this a waste of effort, skip it.

**Comment by JNechaevsky** [comment]
Agreed, remembering the very latest issue with direct aiming, probably this one should not be considered as critical. Another important thing for Windows OS - there are few tools which will allow to show real fps as on-scree-display in game windows (Bandicam, Fraps).

**Comment by fabiangreffrath** [comment]
Sorry, but it turns out that I couldn't care less about this "issue" and will thus simply close it.
