### ISSUE TITLE
Disable native keyboard mapping by default, like in Choco

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#273]
I cannot figure out any reason to have native keyboard mapping on by default. It adds no advantages and screws up cheats, for example. In Choco it is disabled by default.
And not only that: why not set the default jump to Space and use to E? I think most users will like that.

**Comment by fabiangreffrath** [comment]
I'd be happy to reset this value back to its default, but judging from this page setting it to "use native keyboard mapping" sounds like the most reasonable thing to do:
https://www.chocolate-doom.org/wiki/index.php/Setup/Keyboard_configuration

To me it sounds like the issues you experience with your keyboard should be mitigated by enabling this?

**Comment by Zodomaniac** [comment]
>To me it sounds like the issues you experience with your keyboard should be mitigated by enabling this?

No, I thought it caused troubles to @JNechaevsky with taking screenshots.

**Comment by fabiangreffrath** [comment]
> No, I thought it caused troubles to @JNechaevsky with taking screenshots.

Please confirm whether it causes trouble or not, before I switch it back to the default. Thanks!

**Comment by fabiangreffrath** [comment]
From `src/i_input.c`:

```
// If true, keyboard mapping is ignored, like in Vanilla Doom.
// The sensible thing to do is to disable this if you have a non-US
// keyboard.

int vanilla_keyboard_mapping = false; // [crispy]
```

**Comment by fabiangreffrath** [comment]
That's again personal preference. I, for example, couldn't play Doom with Space not being "use". And "jump" being bound to '/' is the default for Hexen and Strife already, so this won't be changed.

**Comment by Zodomaniac** [comment]
I have come up with the case that proves reasonable to turn off native keyboard mapping by default. If a player new to Crispy has Russian keyboard layout on and tries to type in a savegame name, he/she won't be able to do it and will be confused, suspecting a bug.

**Comment by fabiangreffrath** [comment]
> has Russian keyboard layout on and tries to type in a savegame name, he/she won't be able to do it and will be confused

Could you explain what happens then which make it appear as a bug?

**Comment by Zodomaniac** [comment]
Imagine: you are new to Crispy and you cannot type in a savegame name, you hit the keys but no letters are typed, doesn't that feel like a bug?

**Comment by Zodomaniac** [comment]
Why upstream? In Choco the native keyboard mapping is disabled by default.

**Comment by fabiangreffrath** [comment]
I have added the upstream flag because I will have to sort this out with upstream, i.e. fraggle. I am afraid I still don't entirely understand the feature and what changes the switch makes.

**Comment by JNechaevsky** [comment]
@Zodomaniac, am I getting right, that you can type all the characters while native keyboard mapping if off, and not all of them while mapping is on?

I'll check out Crispy in the evening, but AFAIR, in RD all the chars are typing correctly with and without native mapping, with both English and Russian keyboard layouts. Can't say for sure, is it OS dependent, or something was changed in Choco code base since 3.0.0 beta (on which RD is based). Need to investigate it more deeply.

**Comment by Zodomaniac** [comment]
@JNechaevsky 
>am I getting right, that you can type all the characters while native keyboard mapping if off, and not all of them while mapping is on?

Yes, quite right.

**Comment by fabiangreffrath** [comment]
> I'll check out Crispy in the evening, but AFAIR, in RD all the chars are typing correctly with and without native mapping, with both English and Russian keyboard layouts.

@JNechaevsky Could you confirm that this is a port issue and not an OS setting issue on @Zodomaniac's side, please?

**Comment by JNechaevsky** [comment]
Uh-oh. Forgive me my sclerosis, I have spent yesterday's evening with uncapped code. I will check today.

**Comment by Zodomaniac** [comment]
Yes, it's really an upstream issue as Choco behaves the same when typing savegame names with native keyboard mapping.

**Comment by JNechaevsky** [comment]
Confirmed, keys are not accepting in save game fields with `vanilla_keyboard_mapping 1` if I have a Russian keyboard layout. Same in latest dev build of Choco.

In RD they are accepting fine (remember, they are still English chars just visually replaced to Russian).

Will check out Debian soon.

**Comment by JNechaevsky** [comment]
Yep, it's same on Debian. @fabiangreffrath, could you please take a try to type German `ß` char while in `vanilla_keyboard_mapping`? It should print English `h`, I think...

**Comment by JNechaevsky** [comment]
The problem starts here: https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/m_menu.c#L2358. Solution is:

```
    // Savegame name entry. This is complicated.
    // Vanilla has a bug where the shift key is ignored when entering
    // a savegame name. If vanilla_keyboard_mapping is on, we want
    // to emulate this bug by using ev->data1. But if it's turned off,
    // it implies the user doesn't care about Vanilla emulation:
    // instead, use ev->data3 which gives the fully-translated and
    // modified key input.

--- if (ev->type != ev_keydown)
--- {
---     break;
--- }
--- if (vanilla_keyboard_mapping)
--- {
---     ch = ev->data1;
--- }
--- else
--- {
---     ch = ev->data3;
--- }
+++ if (vanilla_keyboard_mapping)
+++ {
+++     ch = key;
+++ }

    ch = toupper(ch);

    if (ch != ' '
     && (ch - HU_FONTSTART < 0 || ch - HU_FONTSTART >= HU_FONTSIZE))
    {
        break;
    }
```

Not sure is it perfectly right, but this way it was done in the Choco 3.0.0 Beta. But this way shift'ed keys isn't working, i.e. by pressing `SHIFT`+`1`, only `1` char will appear, instead of `!`.

**Comment by JNechaevsky** [comment]
Update: Russian chars are not typing because with `vanilla_keyboard_mapping` game apparently tries to print literally Russian chars, which are obviously not presented in the code (a) and font gfx array (b). For example, none of Russian alphabetical char are accepting, but I still can type `SHIFT`+`2` and get a `"` symbol.

Why not `@`? Here, in Russian keyboard layout it's a `"`, not `@` (pink chars are Russian layout):

![kbd](https://user-images.githubusercontent.com/21193394/39938174-bface0be-555a-11e8-8394-e44791883bff.png)
