### ISSUE TITLE
After merging Choco master branch, please add a Crispness Visual option to restrict the aspect ratio to internal Doom's 16:10

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#278]
This commit to Choco https://github.com/chocolate-doom/chocolate-doom/commit/bdb14111e00c37da25fbbb863d4b93088bf88469 removes forcing the 16:10 aspect ratio without the AR correction. I'd like to keep the option to force 16:10 AR with black borders on 16:9 or other monitors, to me it just feels proper, and 16:9 or wider makes sprites look too broad IMO (e.g. in 16:10 Cacodemons. Pain Elementals and powerup spheres look perfectly spherical).
Or is this point valid for Choco as well?

**Comment by fabiangreffrath** [comment]
As far as I understand it, the AR is still enforced until you explicitly set height and width values in the config file. But I am glad you raised the same concern in Choco as well, because I am not going to deviate from upstream in this regard.

I admit, I didn't have any time to have a look at the latest Choco changes, but I already know that this will be one of the more painful merges  -- mostly because of the changes to MAP33 handling, which I had already solved in Crispy some 4 years ago...

**Comment by fabiangreffrath** [comment]
I'll stick to this for Crispy:
https://github.com/chocolate-doom/chocolate-doom/issues/968#issuecomment-375932205
