### ISSUE TITLE
When recording a demo in Doom 2 BFG Edition, triggering the exit from MAP02 to MAP33 takes me to MAP01, and completing MAP33 (warped to) when recording a demo causes a crash

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#280]
### Background

Version of Crispy Doom: Git 31.03.2018

Operating System and version: Windows 7

Game: Doom 2 BFG Edition

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior: Triggering the exit from MAP02 to MAP33 takes me to MAP01, and completing MAP33 (warped to) when recording a demo causes a crash.

Expected behavior: I expected to be taken to MAP33 from the secret exit of MAP02, and be taken to MAP03 on completion of MAP33 like without demo recording.

**Comment by fabiangreffrath** [comment]
This feels a bit redundant given the discussion in https://github.com/fabiangreffrath/crispy-doom/issues/269. Anyway, when recording a demo, we must follow exactly Vanilla's level progression -- else our demos will desync. Same applies to playing a network game, because we must stay in sync with Chocolate clients.

The crash must not happen, though, thanks for noticing that!
