### ISSUE TITLE
Crouching?

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/crispy-doom#287]
Do we need crouching? I guess it can be implemented rather straightforward based on Hexen's morph code, i.e. pig mode. 

### Background

Version of Chocolate Doom:

Operating System and version:

Game: (Doom/Heretic/Hexen/Strife/other)

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior:

Expected behavior:

**Comment by Zodomaniac** [comment]
If we already have jumping, why not?

**Comment by JNechaevsky** [comment]
Well. In my opinion, it's not a bad feature in general. But if we are speaking about 132 vanilla levels of D1, D2, TNT and Plutonia... Where do you want to crouch? None of vanilla maps are supposed do crouch anywhere, as well as jump to. Jumping may be barely considered as mapping standard, and crouching is even more rare thing.

I really have nothing against stuff like jumping and crouching - giving a player some more additional controls is not a bad thing, but we also **ALWAYS** have to remember: it **WASN'T** by design initially. Some things should be left for modding in modding-style source port like (Q/G)ZDoom, or for source ports that's aren't declared as vanilla 100% compatible.

**Fabian**, I want you to get me right here: I am a moderate vanilla purist and I want you to understand the bridge you will cross here. Ability for player to have some additional control of his/her Doomguy is a good thing, absolutely. But you must keep in mind that some things are not supposed to happen to preserve some ... necessary conservatism. Please remember that Crispy is declared as one of most vanilla compatible project, and maybe some even non-technical but **MORAL** aspects should be strictly preserved.

In more short and clear words: I have to say that I'm strictly against this feature. It's a direct interruption into a vanilla game mechanics. Crispy not a source port for this.

**Comment by fabiangreffrath** [comment]
@Zodomaniac @JNechaevsky Thank you very much for sharing your thoughts!

> D1, D2, TNT and Plutonia... Where do you want to crouch?

This is an absolutely valid question and I should have probably asked myself this before I posted this suggestion. Does anybody know of a single place in any IWAD where crouching would actually be helpful?

>  I have to say that I'm strictly against this feature. It's a direct interruption into a vanilla game mechanics. Crispy not a source port for this.

Even if this isn't bound to any key by default and thus needs to be "discovered" in the setup tool?

**Comment by JNechaevsky** [comment]
> Does anybody know of a single place in any IWAD where crouching would actually be helpful?

I think I do, after my many very attentive passes through of all D1 and D2 maps (bmaps and p_fixes). There is a place in MAP05 in HoE, where an iron bars is placed: http://priscree.ru/img/1b5e6bed22f52f.png.

These bars as well as other ones near are not set as blocking. Normally, alive player will never be able to get pass through them, but dead player with reduced height can slip though them (even without a Torque). Maybe there will be a chance when crouched will be able to crouch through these bars... Maybe not.

> Even if this isn't bound to any key by default and thus needs to be "discovered" in the setup tool?

Oh well... Gritting my teeth I must agree that this approach seems to be acceptable. But again, please also remember about player's sprite not in 1st person view.

**Comment by bradharding** [comment]
TBH I'm considering not going ahead with implementing crouching DR for the very reasons you guys bring up.

**Comment by fabiangreffrath** [comment]
I see. AFAICT, Hexen even changes the player's mobj_t in order to deal with the changed dimensions, i.e. height, which is definitely far beyond the red line for Crispy.

**Comment by JNechaevsky** [comment]
Colleagues, I'm really happy to see you are making a right choices about crouching. And yet another my annoying example: imagine we are making a source port not for Doom, but chess board game. For example, we want to implement additional move for the pawn figure, after some conditions or initially, matters not.

- Can it implemented? Yes, surely.
- Can it be optional? Yes, of course.
- But should it be done after all? No. This is not right way to go, because this way a game will no longer can be called a Chess. Some rules are rules, no need to rewrite them.

This example is a bit abstract, but I'm sure you've got it's Idea.

**Comment by fabiangreffrath** [comment]
Okay, since we mostly concordantly agreed that this is neither a necessary nor life-enhancing feature, I close this request.

**Comment by fabiangreffrath** [comment]
As a data point, this is how crouching is done in CDoom 2.07:
```
  if (demo_version >= 207)
    {
      player->mo->height = player->mo->info->height;
      if (cmd->buttons2 & BT2_CROUCH)
	player->mo->height =
	  player->viewheight /= 2, player->deltaviewheight = 0;
    }
```
