### ISSUE TITLE
Test Crispy with Windows 10 April 2018 Update (1803)

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#306]
I should test latest Crispy dev build (x86 with libsample rate), on clean live (non-virtual) Windows 10 x64 build. Thank you Microsoft for yet another bunch of telemetry/diagnostics features, as well as killing ability to switch keyboard layout by "Ctrl+Shift".

Oh well, things to check:

#### Video

- :white_check_mark: Fullscreen / windowed mode changing
- :white_check_mark: Minimizing / restoring
- :white_check_mark: Resizing
- :white_check_mark: Moving from one monitor to another

#### Sound

- :white_check_mark: Sound should work fine, without noise
- :white_check_mark: OPL modes, midi _(sorry, no idea how to test music packs!)_

#### Inputs

- :white_check_mark: Standard and non-standard key bindings should work fine
- :white_check_mark: Mouse should not behave jerky

#### Stress-test

- :white_check_mark: Nova, Nuts and Sunder wads should work fine in extreme-calculations places

#### Demos

- :white_check_mark: Run all vanilla demos with `-timedemo` (just in case)
- :white_check_mark: Run some kind of speerun demos with both `-playdemo` and `-timedemo` [lvalln2114.zip](http://doomedsda.us/lmps/945/3/lvalln2114.zip)

#### Other

- Just "run and leave" Crispy for few hours, somewhere in any level, in unpaused state
- Anything else? Any ideas, suggestions, requests?

**Comment by fabiangreffrath** [comment]
This sounds sure like a neat idea, but is more like a smoke-test for SDL than for Crispy itself. Crispy, and its code base Choco, are programmed in a *mostly* portable, system-independent way (taking aside e.g. direct OPL access or file I/O). All interaction with the underlying system happens through the SDL abstraction layer. So if you ever experience issues like lagging mouse or distorted sound, this is most likely due to a bug in SDL - because I know for sure that Crispy itself works well, though on a different system with different boundary conditions.

**Comment by JNechaevsky** [comment]
Oh, sure I know and understand that if something will go wrong, it's a SDL-related issue, and for what actually SDL stands for. But yet still I want to be 100% sure that everything is fine. 

Just remember different behavior in Choco's https://github.com/chocolate-doom/chocolate-doom/issues/994, when Windows executable was having a crash, while Linux and vanilla DOS are not.

**Comment by JNechaevsky** [comment]
All tests has been done, everything is fine. The only thing that I have noticed - flats are now looking correct on Sunder's MAP11, (not related to this issue, but cool).

Guess this ride is closed. Now I finally can go back to Win7, again. :relieved:
