### ISSUE TITLE
Clarify that 'Highlight on target' works when autoaim is on

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#312]
### Background

Version of Crispy Doom: Daily autobuild May 7 https://github.com/fabiangreffrath/crispy-doom/commit/d76329136920a48a86ee2a2c63b2a22428f4c309

Name the item `Highlight on target in autoaim`

BTW, the new setting values for crosshair must be hidden when the crosshair is off, like the 'Crosshair shape' value is.
![doom0058](https://user-images.githubusercontent.com/15119473/39690551-2f8c5296-51e3-11e8-8da1-38b9d4f93dd6.png)

**Comment by fabiangreffrath** [comment]
Thank you very much! I am glad that you guys test the new features much more thoroughly than I do. ;)

**Comment by fabiangreffrath** [comment]
Ah, this you mean! Well, actually, no. On second sight I don't even like the fact that there i no setting displayed, it should at least read "none". I will fix that!

**Comment by Zodomaniac** [comment]
There still is one imperfection: even though vertical aiming is set to 'Direct', the crosshair highlights when it's vertically off target
![doom0066](https://user-images.githubusercontent.com/15119473/39752900-87e2e1fc-52c5-11e8-8576-ac78ced04ce0.png)

**Comment by fabiangreffrath** [comment]
Oh, I see. This is, because in Doom you can shoot with a specific slope, but you cannot aim with one. Have a look at the different parameters that get passed over to `P_AimLineAttack()`
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/p_map.c#L1198
and `P_LineAttack()`:
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/p_map.c#L1242

Sorry, but I guess this is about as far as that feature goes...
