### ISSUE TITLE
Attack sounds in cast sequence don't play for any character except Doomguy if Smooth monsters WAD is applied

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#357]
The attack sounds for all monsters except Doomguy don't play at all when using the Smooth monsters add-on.
[SMOOTHED.zip](https://github.com/fabiangreffrath/crispy-doom/files/2633169/SMOOTHED.zip)
The alert sounds do play though.

**Comment by Zodomaniac** [comment]
Smooth monsters add-on isn't supported by Choco at all.
Crispy daily build from November 6 also has this bug.

**Comment by fabiangreffrath** [comment]
Ah, sure, I forgot about Smooth and Choco. :confused: 

Well, that's because SMOOTHED.wad has shuffled around pretty much every state in the state table - and sounds in the cast sequence are played based on state. For example, the Zombieman's attacking state in Vanilla is `S_POSS_ATK2`, so the pistol sound is played when this state is reached in the cast sequence. Now, if SMOOTHED.wad has moved his attacking state to a different state number, the engine cannot know and simply plays no sound at all.

This would be a lot easier to fix, if `S_POSS_ATK2` was the Zombieman's `->missilestate`, but it's actually one state later (the first one merely calls `A_FaceTarget()`)...

Sorry, but currently I have no plans to go through the pain to implement a cast sequence fix for mods that decide to mess up the state table.

**Comment by fabiangreffrath** [comment]
Maybe the more relevant question is: "Does this even work properly in GZDoom?"

See, everything is pretty much hard-wired here (and it is called "sound hacks" in the comments!):
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/f_finale.c#L522

It could make sense, though, to play the sounds based on the current monster's current state's action function. But then, that would be a pretty invasive change in something that is already called a hack, and, well, it's the cast sequence and the only benefit would be with some very invasive mod loaded. This is really very low on the priority ladder, sorry.

**Comment by fabiangreffrath** [comment]
Starting to like the idea outlined in the previous post... though, still pretty low priority!
