### ISSUE TITLE
Uncapped frame rate question

### ISSUE THREAD

**Issue by Wintermute0110** [fabiangreffrath/crispy-doom#363]
This is not an issue but rather a question. I'm doing it here because registrations in the Doomworld forum are disabled.

I'm trying to understand how **uncapped framerate** works. I'm looking for a new Doom source port candidate to become a libretro core. The current PrBoom core has a lot of problems as pointed out in [this issue](https://github.com/libretro/libretro-prboom/issues/7).

I run Crispy Doom in Linux with a display frame rate of 60. If I disable `Uncapped frame rate` and `Enable VSync` then doom runs at 35 FPS in windowed mode (measured with **IDRATE**). If I enable Vsync, the game runs smoother and at 35 FPS. If I enable `Uncapped frame rate` doom keeps running at 35 FPS. If I restart Crispy Doom with `Uncapped frame rate` ON still runs at 35 FPS.

Can you please explain how Uncapped frame rate works? If Crispy Doom runs at 60 FPS with Uncapped frame rate the Doom engine speed will be the correct one? Thanks a lot.

**Comment by fabiangreffrath** [comment]
> If I enable `Uncapped frame rate` doom keeps running at 35 FPS

Wait a minute. With "Uncapped Framerate" ON, Crispy Doom is supposed to run at arbitrarily high framerates or - with VSync ON - at your screen's refresh rate. IDRATE is supposed to reflect that. Could you please confirm?

**Comment by Wintermute0110** [comment]
Confirmed. In the config file `uncapped framerate` is **ON**.
```
cat ~/.local/share/crispy-doom/crispy-doom.cfg | grep uncapped
crispy_uncapped               1
```

Then, I run `crispy-doom -iwad doom.wad -warp 3 5` and show the FPS with `IDRATE` and it shows 35 FPS. In the menu `Uncapped framerate` is ON. I'm using a compile version of commit `c2315159`.

**Comment by fabiangreffrath** [comment]
Something is wrong with your configuration. The size of `struct crispy_t` has changed recently. Please run `make clean && make` from the top-level source directory and try again.

Let's get this fixed first and talk about the details later.

**Comment by Wintermute0110** [comment]
OK, so I did more tests. First, I compiled release 5.3
```
$ git checkout crispy-doom-5.3
$ ./configure && make clean && make -j8
```

I get the following

| Uncapped framerate | VSync | FPS |
|-----------------------------|----------|--------|
| OFF | OFF | 35 FPS |
| OFF | ON | 35 FPS |
| ON | OFF | 540 FPS |
| ON | ON | 60 FPS |

When Uncapped framerate is ON the game runs ultra smooth. The difference is huge! I understand some purists and speedrunners may feel some differences (I understand that not all the gameticks run exactly at the same time intervals) but for the average user the improvement with Uncapped framerate is spectacular.

Now, if I compile current version in master:
```
$ git checkout master
$ ./configure && make clean && make -j8
```

Uncapped framerate does not work anymore, whatever the settings.

One question: did you take the Uncapped framerate implementation from PrBoom+? I think you and Andrey have exchanged code between PrBoom and Crispy Doom, right?

**Comment by fabiangreffrath** [comment]
You will have to run the snapshot build with `-oldsync`. I'll fix that!

**Comment by fabiangreffrath** [comment]
Alright, now that the bug has been sorted out [1], thank you very much for spotting and let's reply to your initial request. I'll try to keep myself short, the topic is quite complex.

Generally, the game engine "thinks" 35 times per second. By doing so, it re-evaluates the entire game state. Each time it does so, the `gametic` variable is increased, so the time between two successive gametics is 1/35 second. This happens in `TryRunTics()` in https://github.com/fabiangreffrath/crispy-doom/blob/master/src/d_loop.c#L795

Once a tic has been calculated, the engine renders the updated game scene, see `D_RunFrame()` in https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/d_main.c#L508 and subsequent lines. The function `D_RunFrame()` is running in an endless loop, so once the scene is rendered, the game state is re-evaluated again in `TryRunTics()`. 

However, the next gametic isn't calculated immediately. There is a loop in `TryRunTics()` which lets the process sleep until enough time has passed for the next gametic, i.e. 1/35th of a second.

Instead of sleeping until the next tic is calculated and then rendered, you could leave this function early and the current scene will be rendered again. This is what happens here and quite technically, this already **uncaps** the framerate, because the scene is rendered again and again independent of the engine's thinking frequency of 35 Hz.
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/d_loop.c#L714

However, this doesn't buy you much, because the exact same scene will be rendered several hundred times per second until finally a new gametic is calculated after the next 1/35 second. So the crucial part is **interpolation**. This means that between two subsequent calls to the renderer the rendered scene (not the calculated one!) is interpolated between the previously calculated tic and the next one - based on position and momentum. This happens with the help of the "fractionaltic" variable which is updated whenever a scene has been rendered to the screen:
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/i_video.c#L833

So, in short this means that the game state is re-calculated 35 times per second, regardless of the uncapped framerate feature being enabled or not. The game runs at the exact same speed (logically, not in terms of rendering) and is still demo compatible and network compatible with Chocolate Doom or other compatible ports without that feature. The one thing that's different is that the rendered scene deviates from the calculated scene depending on how far we are between two gametics.

> did you take the Uncapped framerate implementation from PrBoom+? I think you and Andrey have exchanged code between PrBoom and Crispy Doom, right?

No, the initial implementation has been contributed by @AlexMax in 2015 and got a bit adjusted and extended since then. I did exchange some code with Andrey, i.e. I took some code from PrBoom+ and contributed back some other, but he has been very inactive since then. He didn't even bother to apply the latest patch I sent to him in order to fix building against the recent libdumb back in June.

Hope that helps!

Cheers,

 -- Fabian

[1] Until the latest two commits to Crispy were applied, the uncapped framerate feature only worked for the "old" network syncing code. Nobody ever realized this, because that "old" code was the default, until fraggle changed the "new" code to become the default in a recent commit to Chocolate Doom which I merged into Crispy. However, now the feature works for both code paths.

**Comment by Wintermute0110** [comment]
I have tested the last version in master and everything is all right now, thanks a lot. However, some minor issues (I can open another issues if you wish):

 * With `Uncapped framerate` ON and `VSync` ON, game is running at 60 FPS. If I open the menu (with ESC) the FPS drop to 35. FPS go back to 60 when the menu is closed.

 * Same conditions as before, if the game is paused FPS drop to 35.

 * With screensizes 9 and 10 the background sprites of the status bar are shown in the automap mode. I think when the automap mode is ON the status bar should look the same as when the automap is overlaid with `O` key. This is not really a bug, just an aesthetic suggestion.

Thanks a lot for your superb explanation! It will be very helpful for my project! [Kodi](https://kodi.tv/) and Retroarch are in desperate need of a Doom core with Uncapped framerate.

**Comment by fabiangreffrath** [comment]
The first two items are actually on purpose, that's the `leveltime > oldleveltime` condition here https://github.com/fabiangreffrath/crispy-doom/blob/HEAD/src/d_loop.c#L685

In single player mode, having the game paused or in the menu effectively stops the game, so no further game state calculations are done. Thus, it makes no sense to go "full throttle" and render more than the capped 35 frames per second at all. In multiplayer mode, the game will keep rendering with uncapped framerate, even if the menu is open or a single player paused the game.

**Comment by Wintermute0110** [comment]
Thank you for the clarification. Yeah, I understand your reasoning. However, when running Doom on big LCD screens and the signal goes through HDMI Kodi needs the frame rate to be constant, otherwise you get artefacts. Anyway, it is a minor issue not related to Crispy and thanks to your explanations I have a good understanding of how UFR works to fix PrBoom+.

My wish would be to port Chocolate/Crispy to libretro. However, proper gamepad support requires a lot of changes and fraggle and jmdt will not allow them. I think the best bet right now is to fork PrBoom+ and take some nice feats from Crispy. Let's see how things go in the following months :)

**Comment by fabiangreffrath** [comment]
> However, when running Doom on big LCD screens and the signal goes through HDMI, Kodi needs the frame rate to be constant, otherwise you get artefacts.

That's what we have VSync for. Each time the screen refreshes it will get passed a frame. It is just that the renderer will not necessarily have rendered a **newly calculated** frame during each refresh. That's why the IDRATE cheat still shows 35FPS, but the screen nevertheless refreshes with its native rate.

> My wish would be to port Chocolate/Crispy to libretro. However, proper gamepad support requires a lot of changes on top of UFR and fraggle and jmdt will not allow them in Chocolate. 

Sorry, but this is just not true! Improved gamepad support is definitely on the agenda for Choco and there is even some work in progress going on, e.g.

https://github.com/chocolate-doom/chocolate-doom/pull/1076
https://github.com/chocolate-doom/chocolate-doom/pull/1112

> I think the best bet right now is to fork PrBoom+ and take some nice feats from Crispy.

He? What's technically speaking against a Crispy port for libretro? Apart from Boom support, that is?

**Comment by fragglet** [comment]
Which were the gamepad changes which were turned down, out of curiosity?
