### ISSUE TITLE
Play demon alert sounds fully when "Play Sounds In Full Length" is enabled

### ISSUE THREAD

**Issue by BCG2000** [fabiangreffrath/crispy-doom#369]
Before making this, I took a basic look at how the sound code works. I understand that whenever an origin starts playing a new sound or is destroyed, the previous one will be stopped. It's an engine limitation, so if for some reason this is not feasible, I will understand. Now as for the issue...

When a demon spots me, its alert sound (the scream they make) gets cut off as soon as it moves or starts attacking. It's really jarring, like when facing the Spider Mastermind in E3M8 because its scream will be cut off almost all the time.

My suggestion is to make an exception to this and let the alert sound play fully, like you did for rockets and exploding barrels. The only problem I can see when it comes to implementing this is when the demon gets immediately killed after it spots you (i.e. blasting an Imp the moment it sees you). But I guess it's possible to come up with a way to stop the alert sound as soon as the demon dies in that case.

This source port is pretty much perfect for what I need it to do but the alert sounds cutting off really get in the way. Other source ports I have used don't have this problem (I know it's because they rewrite a lot of code and change stuff around). I just wish Crispy Doom had this feature as well, it could even be a separate Crispness option if you want to. That's all, thanks in advance.

EDIT: I forgot to mention that the "A Secret Is Revealed" and item pickup sounds also tend to cut off a lot of the time, it's jarring too. If possible, I suggest an exception for these as well so they always play fully, I think this one may be simpler to do.

**Comment by fabiangreffrath** [comment]
Thank you very much! I like the idea and it fits perfectly to the "Play Sounds in Full Length" feature.

> The only problem I can see when it comes to implementing this is when the demon gets immediately killed after it spots you (i.e. blasting an Imp the moment it sees you). But I guess it's possible to come up with a way to stop the alert sound as soon as the demon dies in that case.

Actually, it's not that easy, as there is no "stop sound" function for the sounds emitted from the fake sound objects (an implementation detail, forget about it). So, "full length" really means "full length" here. But, anyway, I don't think it is much of an issue if alert sound and death sound overlap if both events are so close to each other. :wink:

I'll see what I can do about item secret revealed and item pickup sounds.

**Comment by BCG2000** [comment]
So I learned about your daily builds and could finally test this fix. It seems there was a small improvement (probably placebo) but the seesounds still cut out a lot of the time. Again I test this with the Spider Mastermind (on E3M8 of DOOM.WAD), but it still happens with others like the Revenant.

I have the "Play Sounds In Full Length" enabled as well as 32 Sound Channels. Considering that when I met these two demons it was just them and a few others, there is no lack of sound channels to play the sounds.

I would record and upload a video to better demonstrate the issue, but currently I'm having severe internet problems due to events in my country.

**Comment by fabiangreffrath** [comment]
Cannot confirm. 

Alright, here is a little test map. Approach the Revenant and he will instantly start attacking you. If you have the feature disabled, you will hear his seesound interrupted - if you hear it at all. With the feature enabled, though, you will be able to hear it at full length.

This confirms that the feature works in principle. I have no idea why it shouldn't work for you then. :confused: 

[seesound.zip](https://github.com/fabiangreffrath/crispy-doom/files/2738273/seesound.zip)

**Comment by BCG2000** [comment]
Okay, that works as expected. There are times where the alert sound doesn't play but I noticed it's because attacking the Revenant before it spots you can make it skip playing its alert sound since it goes straight to attack mode, so nothing to do with the issue.

And with this observation I found the real source of this, but it's not that simple... The alert sounds are cut off by item pickup sounds on E3M8 of DOOM.WAD (Spider Mastermind) but not on MAP21 of MASTERLEVELS.WAD (Revenant):

E3M8: Run straight to the Rocket Launcher pickup but don't pick it up yet. Shoot your Pistol and as soon as you hear the Spider Mastermind's alert sound, pick the weapon up and the alert sound will always cut off.

MAP21: After you spawn, open the door immediately behind you and approach the Chainsaw pickup but don't pick it up yet. Shoot your Pistol and as soon as you hear the Revenant's alert sound, pick the weapon up and the alert sound will never cut off.

Now I don't know why this difference in behavior. I'm guessing it's because the first case is a boss or because of this unique sound behavior: https://doom.fandom.com/wiki/Sound_effects_behave_differently_on_level_8

Maybe it's both. This is my guess because the exact same thing happens in MAP08 of DOOM2.WAD. If you open the door of the room full of Barons with the Cyberdemon and then run straight to the Supercharge (blue ball), the Cyberdemon's alert sound will cut off every single time too.

It's unfortunate that such a simple fix had to have a complicated edge case. While we are at it, any idea yet about making item pickup sounds and secret revealed sound play in full length?

**Comment by fabiangreffrath** [comment]
> And with this observation I found the real source of this, but it's not that simple... The alert sounds are cut off by item pickup sounds on E3M8 of DOOM.WAD (Spider Mastermind) but not on MAP21 of MASTERLEVELS.WAD (Revenant):

Ah, I think I can explain that.

In Doom, you either play a sound at the sound source's location (then it is connected to an object on the map) or you play it "in the player's head" with full volume and symmetrical stereo separation. Sounds emitted by monsters *usually* belong to the first category, whereas item pick-up sounds and the secret-revealed sound belong to the latter.

I said usually, because of this:
https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/p_enemy.c#L665

This means that seesounds emitted by spiders and cyberdemos are always emitted at full volume, i.e. in the player's head without a corresponding sound source on the map. This, in turn, means that any further sound emitted in the player's head, e.g. a weapon pick-up sound, will interrupt these monsters' seesounds - because you cannot emit two sounds from the same source.

> Now I don't know why this difference in behavior. I'm guessing it's because the first case is a boss or because of this unique sound behavior: https://doom.fandom.com/wiki/Sound_effects_behave_differently_on_level_8

This bug meant that sounds were never cut off even if the sound source was too far away to recognize. It is fixed with the "Misc. Sound Fixes" feature, though, at least for Doom 2 and Ultimate Doom Episode 4.

> It's unfortunate that such a simple fix had to have a complicated edge case. While we are at it, any idea yet about making item pickup sounds and secret revealed sound play in full length?

Since these sounds are all played in the player's head, and thu sinterrupt each other if played in succession, this issue is very similar to the one I described above. Fixing the issue for the boss monsters' seesounds will also fix the issue of pickup sounds interrupting each other.

I have an idea that I'll need to test. :wink:

**Comment by JNechaevsky** [comment]
Maybe this idea will be handy: couple of time ago, I've made a separate function for unbreakable NULL-sourced sounds: https://github.com/JNechaevsky/russian-doom/commit/4a7fdd5b328502069a38dfbae7cb43c3e1a47093

Kinda dirty, but if I'm remembering correctly, the idea is to put playing sound to the last channel. 

Beware! Pain sound of Icon of Sin **should** have a break, otherwise player may become literally deaf after making a double-barreled point blank to the head.

**Comment by fabiangreffrath** [comment]
Nice idea, thanks! However, I'd like to avoid having another `S_StartSound()` duplicate in the code.

It seems to me, that two identical sounds interrupt each other (e.g. two item pickup sounds) but two different ones don't. That's a solution I could well live with.

**Comment by BCG2000** [comment]
I can confirm, identical sounds cancel each other but different ones don't. That's actually how I think it should be, to avoid a room of full items or multiple secrets in sucession using up all sound channels (I suppose that's what would happen).

It's working just like I wanted. Secret revealed sound never cuts off now, same for the boss alerts (I can now hear a Spider Mastermind and Cyberdemon alerting at the same time without cutting off). It stopped being jarring.
