### ISSUE TITLE
Music pack?

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [fabiangreffrath/crispy-doom#388]
Where did it go? Is it still supported in Crispy Doom?
I don't see it linked in https://github.com/fabiangreffrath/crispy-doom/blob/master/README.md, and it has been removed from the Chocolate Doom Wiki too.

**Comment by fabiangreffrath** [comment]
No, I am not going to support this anymore. People kept on reporting problems with the SDL libraries that I used to ship - which support soundfonts via fluidsynth - which were resolved by repalcing them with the ones from the Choco release or the daily build - which are missing this feature.

I am not using Windows myself and have already  invested so much time into these issues that I was close to throwing the towel for this project. In order to preserve my mental health and maintain a lower level of frustration, I decided not to care anymore.

Anyone is invited to do the additional work and provide more feature rich SDL libraries for Crispy, but that won't be me anymore, sorry.

**Comment by nbmrjuhneibkr** [comment]
I've never had any issues with the music pack, other than music being much louder than the sound effects (which can be easily fixed by adjusting volume levels in the options).

I understand that you may not want to work on this anymore, but removal of the music pack without providing any replacement is a regression. After playing Crispy Doom with the music pack, I can't imagine going back to the standard OPL audio.

I've tested http://www.greffrath.com/~fabian/crispy-doom-music-pack_5.1.zip with the current release (5.4), and it seems to work fine, like it always did. Maybe you should at least add it back to the README (with a warning that it's not officially supported anymore) until a better alternative is available.

**Comment by fabiangreffrath** [comment]
I'll probably add an entry to the FAQ section in the Wiki. There is a chance that the SDL_Mixer libraries used in the daily builds will gain support to dlopen the fluidsynth library. This would make things much easier, but it is not decided yet.
