### ISSUE TITLE
Extra slash in music pack and autoload paths compared to Choco

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#390]
### Background

Version of Crispy Doom: 5.5.1

Operating System and version: Win 7

Game: (Doom/Heretic/Hexen/Strife/other)

Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior:

Extra slash in the path after Roaming in crispy-doom.cfg entries
```
autoload_path                 "C:\Users\username\AppData\Roaming\\crispy-doom\autoload"
music_pack_path               "C:\Users\username\AppData\Roaming\\crispy-doom\music-packs"
```
compared to Choco's
```
autoload_path                 "C:\Users\username\AppData\Roaming\chocolate-doom\autoload"
music_pack_path               "C:\Users\username\AppData\Roaming\chocolate-doom\music-packs"
```

Expected behavior:
There should be no difference, I think

**Comment by fabiangreffrath** [comment]
Well, this won't hurt. Anyway, what happens if you remove these two lines from the config file and restart the game? And do you compare the Crispy release with Choco daily builds or any other combination?

**Comment by Zodomaniac** [comment]
>Anyway, what happens if you remove these two lines from the config file and restart the game?
The 5.5.1 release writes them back for the current username with the extra slash.

>And do you compare the Crispy release with Choco daily builds or any other combination?
Crispy release writes the extra slash, Choco and Crispy daily builds don't.

**Comment by fabiangreffrath** [comment]
I suspected that. We get the base directory for the music packs from `SDL_GetPrefPath()`:

https://github.com/fabiangreffrath/crispy-doom/blob/master/src/m_config.c#L2669

And this function has been fixed to return normalized path names just after the SDL-2.0.5 release:

https://hg.libsdl.org/SDL/rev/083133ba8f9b

Since Crispy releases still use SDL 2.0.5 and both Crispy and Choco daily build have been updated to use SDL 2.0.9, this explains why both generate different path names. Nothing to worry about.
