### ISSUE TITLE
Consolidate extended savegame data into standard data

### ISSUE THREAD

**Issue by JNechaevsky** [fabiangreffrath/crispy-doom#406]
Good morning! I have pretty absurd idea and not sure it's something really necessary, but...

AFAIR, in vanilla Doom there is terminator which is indicating the end of saved data ([here](https://github.com/id-Software/DOOM/blob/master/linuxdoom-1.10/p_saveg.c#L258)). 

What if all extended data will be placed after that terminator in Crispy? This probably will keep full compatibility with vanilla format w/o necessity of activating/deactivating extended format.

Not everything that simple as it gets, but before moving on I'm suggesting to understand - is it worth at all.

_Suggestion №104_

**Comment by JNechaevsky** [comment]
I'm afraid I was too abstract in this suggestion. Here's a simple scheme of suggested savegame reformatting:

![savegame](https://user-images.githubusercontent.com/21193394/56453884-6042c480-6351-11e9-8cc2-856941b7c403.png)

The most hard part probably will be an inserting Crispy data after all common data is loaded, i.e. when everything is ready for loading game world.

**Comment by fabiangreffrath** [comment]
Thank you for your suggestion, but this is *exactly* how it already works - since the very first implementation. Everything that cannot be represented in Doom's own savegame format is added after the EOF byte as key/value pairs. That's why it is still possible to load these savegames from Vanilla Doom, you will just lose the extended information.
