### ISSUE TITLE
Feature request - Sigil support

### ISSUE THREAD

**Issue by buvk** [fabiangreffrath/crispy-doom#418]
Hello. I was wondering whether it would be possible to support Sigil without having to use the compat version.

**Comment by fabiangreffrath** [comment]
Hi,

first of all, there is nothing wrong with the compat version. It has been explicitely crafted for non-Zdoom ports and AFAIK already contains a DEHACKED lump to properly change the map names. Thus, there is not much left to support this. Also, this is the version expected to be used by speed-runners, because it will be the only one natively supported by PrBoom+.

Regarding the non-compat version, it uses a MAPINFO lump to add SIGIL as the fifth episode to Ultimate Doom. Since Crispy doesn't support the MAPINFO lump [https://github.com/fabiangreffrath/crispy-doom/issues/372] (yet, who knows?), I would have to replicate its contained information by hard-coding it into the engine. As you may understand, I am currently very reluctant to do this.

I'll have to check which lumps are in the non-compat version and see what I can make out of it. However, I am currently a bit tired of coding (it will come back, no worries) and would like to rest a bit until the hype around the SIGIL release - which currently gets on my nerves quite a bit - has settled.

https://www.doomworld.com/forum/topic/103430-sigil-new-romero-megawad-release-date-may-31/?page=36&tab=comments#comment-1979196
https://www.doomworld.com/forum/topic/103430-sigil-new-romero-megawad-release-date-may-31/?page=38&tab=comments#comment-1981037

**Comment by fabiangreffrath** [comment]
Hm, as SIGIL.WAD overrides some common assets like e.g. TITLEPIC, how should I handle this if the PWAD gets auto-loaded if detected when starting Ultimate Doom?

**Comment by buvk** [comment]
I personally don't think it should be auto loaded. I think sigil titlepic and new episode should only show up when loaded alongside doom.wad

**Comment by fabiangreffrath** [comment]
At least the v1.0 release of Sigil (haven't checked the v1.1 release yet) the PWAD does contain both a ZMAPINFO and an EMAPINFO lump, but no regular MAPINFO lump. As the former two are specifically crafted to support ZDoom (and derivatives) and Eternity, respectively, I believe a port like Crispy cannot be expected to add support for these. 
As this invalidates the first option, i.e. adding at least minimal support for MAPINFO lumps, only the second option is left, i.e. hard-coding the relevant changes into the engine. I have done this before for NERVE.WAD and other special IWAD maps (e.g. E1M10) and reportedly IDCLEV51 already works to some extend, so the impact of changes might come out less severe than I expected.

Regarding auto-loading: If I add support for this, SIGIL.WAD will get auto-loaded but it won't stand in the way. I will integrate it into the episode menu, but it will not change any of the other game assets.

**Comment by fabiangreffrath** [comment]
How about SIGIL_SHREDS.wad? Should this be added if available and SIGIL.wad gets auto-loaded?

**Comment by Zodomaniac** [comment]
> How about SIGIL_SHREDS.wad? Should this be added if available and SIGIL.wad gets auto-loaded?

I think yes)

**Comment by buvk** [comment]
IMHO, if you are auto-loading SIGIL.wad, then, if present, SIGIL_SHREDS.wad should be auto-loaded as well.

**Comment by Zodomaniac** [comment]
I tried the daily build, Sigil can be loaded manually but doesn't autoload with DOOM.WAD.

**Comment by fabiangreffrath** [comment]
Yes, I first need to make sure the episode works correct if loaded manually.

**Comment by Zodomaniac** [comment]
As far as I have seen the episode loads, the music WAD plays, the savegames are named with `Sigil.wad`, `IDCLEV5X` works :) Autoloading TBD ;)

**Comment by buvk** [comment]
Thanks for implementing this.

Just a thought... would it maybe be possible to integrate some crispy features to toggle between assets (E.g. toggle between ultimate doom and sigil TITLEPIC), and have the ability to switch between midi and buckethead music?

**Comment by Zodomaniac** [comment]
>I will integrate it into the episode menu, but it will not change any of the other game assets.

When Shreds WAD is present, it still changes the D_INTRO music.

**Comment by fabiangreffrath** [comment]
> Just a thought... would it maybe be possible to integrate some crispy features to toggle between assets (E.g. toggle between ultimate doom and sigil TITLEPIC), and have the ability to switch between midi and buckethead music?

I don't think so. First, I don't like this "Replace all the things!" mentality for PWADs that are meant to be auto-loaded. Second, if you want to go for "All things Sigil!", you may still load SIGIL_COMPAT.wad and have all your assets replaced. Third, I you do not prefer the SIGIL_SHREDS.wad music, you are free to rename the PWAD or simply move it out of Crispy's WAD search paths.

> When Shreds WAD is present, it still changes the D_INTRO music.

Indeed, this was an oversight. Thanks!

**Comment by Zodomaniac** [comment]
>Second, if you want to go for "All things Sigil!", you may still load SIGIL_COMPAT.wad and have all your assets replaced.

Or load SIGIL.WAD and SIGIL_SHREDS.WAD manually.

**Comment by buvk** [comment]
> Or load SIGIL.WAD manually, then you will have all things Sigil+Sigil's MIDI music, and SIGIL_SHREDS.WAD manually after that to enjoy Buckethead's soundtrack.

Doing it this way changes certain things I do not want to change (E.g. the end of the level music in episodes 1-4).

**Comment by fabiangreffrath** [comment]
@Zodomaniac is right. Either you load the PWADs manually, then you get all the replacements as intended by Mr. Romero. Or you let the engine load it automatically, then you get it seamlessly integrated into The ultimate Doom. This is as far as support for Sigil will go.
