### ISSUE TITLE
With IDDT cheat, Lost Souls are depicted on the automap as green triangles instead of red

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#421]
Nuff said :) Discovered in Sigil E5M1.

**Comment by fabiangreffrath** [comment]
This is because Lost Souls don't count as monsters, i.e. they don't sum up to the Kills statistic. Instead, they are treated like some annoying, dangerous decoration. :grin:

But I agree, they should probably get their own color. I won't color them red, though, because this would mislead player hunting for 100% kills. I'd rather color them orange, e.g. palette color 215.

The question is, should I color them by their `MF_NOGRAVITY` flag, which would include projectiles, missiles, bullet puffs, etc. Or should I color them by their `MF_SHOOTABLE` flag, which would include barrels and boss brains? I think I prefer the latter...

**Comment by fabiangreffrath** [comment]
```
--- a/src/doom/am_map.c
+++ b/src/doom/am_map.c
@@ -1694,6 +1694,8 @@ AM_drawThings
                 t->radius, t->angle,
                // [crispy] show countable kills in red ...
                 ((t->flags & (MF_COUNTKILL | MF_CORPSE)) == MF_COUNTKILL) ? REDS :
+               // [crispy] show other shootable items in orange ...
+                (t->flags & MF_SHOOTABLE) ? 215 :
                // [crispy] ... corpses in gray ...
                 (t->flags & MF_CORPSE) ? GRAYS :
                // [crispy] ... and countable items in yellow
```

**Comment by fabiangreffrath** [comment]
Color 223 is probably even better.

**Comment by Zodomaniac** [comment]
I am for the shootable flag coloring, is it orange? I am at a friend's place and cannot look up.

**Comment by Zodomaniac** [comment]
I let you know my impression in the comment to the commit :)

**Comment by fabiangreffrath** [comment]
I'll have to check it. I want to prevent the Automap from looking like Carnival in Rio.

**Comment by Zodomaniac** [comment]
The barrels will still be brown, so Barrels of Fun MAP23 will be OK, and brown lost souls are kinda hard to track.

**Comment by fabiangreffrath** [comment]
Forcefully moving the discussion to this issue:

> I let you know my impression in the comment to the commit :)

That was this:
"
all the MF_NOGRAVITY things should be colored with bright orange (215), including projectiles and Lost Souls that are themselves like projectiles (emitted by Pain Elemental included), they should be brighter as they are dangerous and moving, and all MF_SHOOTABLE things except Lost Souls should be dark orange/brown (223).
"

And I replied:
"
That would be t->flags & (MF_MISSILE | MF_FLOAT), because there are only three map things with MF_FLOAT, i.e. Lost Soul, Pain elemental and Cacodemon, and the latter two are already covered by the check for the MF_COUNTKILL flag. The rest is missiles. This leaves all other decoration in green.
"

**Comment by fabiangreffrath** [comment]
How about light red color 16 for projectiles and Lost Souls?

**Comment by fabiangreffrath** [comment]
```
--- a/src/doom/am_map.c
+++ b/src/doom/am_map.c
@@ -1694,6 +1694,8 @@ AM_drawThings
                 t->radius, t->angle,
                // [crispy] show countable kills in red ...
                 ((t->flags & (MF_COUNTKILL | MF_CORPSE)) == MF_COUNTKILL) ? REDS :
+               // [crispy] ... show Lost Souls and missiles in light red ...
+                (t->flags & (MF_FLOAT | MF_MISSILE)) ? 16 :
                // [crispy] show other shootable items in orange ...
                 (t->flags & MF_SHOOTABLE) ? 223 :
                // [crispy] ... corpses in gray ...

```

**Comment by Zodomaniac** [comment]
Light red 16 is too pink IMO) I'd rather have it bright orange 215.
And in the comment to the code, I'd call 223 brown, not orange :)

**Comment by fabiangreffrath** [comment]
You mean like this?
```
--- a/src/doom/am_map.c
+++ b/src/doom/am_map.c
@@ -1694,7 +1694,9 @@ AM_drawThings
                 t->radius, t->angle,
                // [crispy] show countable kills in red ...
                 ((t->flags & (MF_COUNTKILL | MF_CORPSE)) == MF_COUNTKILL) ? REDS :
-               // [crispy] show other shootable items in orange ...
+               // [crispy] ... show Lost Souls and missiles in orange ...
+                (t->flags & (MF_FLOAT | MF_MISSILE)) ? 215 :
+               // [crispy] ... show other shootable items in brown ...
                 (t->flags & MF_SHOOTABLE) ? 223 :
                // [crispy] ... corpses in gray ...
                 (t->flags & MF_CORPSE) ? GRAYS :

```

**Comment by Zodomaniac** [comment]
Yes, right, thanks!

**Comment by fabiangreffrath** [comment]
Colors 215 and 223 don't provide enough contrast, they are nearly impossible to tell apart on the Automap. How about some blue for the other shootable items?

**Comment by Zodomaniac** [comment]
I'd suggest 234 for other shootable items, then the contrast will be OK.

**Comment by fabiangreffrath** [comment]
Na, too dark. They were green 112 before. What's against blue? These items are sratic and harmless - i.e. neutral... thus blue. :grin:

**Comment by Zodomaniac** [comment]
Explosive barrels can be not harmless at all! :)

**Comment by fabiangreffrath** [comment]
Are we arguing about Automap colors again... :sob:

**Comment by Zodomaniac** [comment]
Well, about one minor part of the automap)) Please try 216 and 232 colors.

**Comment by fabiangreffrath** [comment]
indistinguishable :frowning_face:

**Comment by Zodomaniac** [comment]
215 and 233 then ;)

**Comment by Zodomaniac** [comment]
If 215 and 233 are also indistinguishable, I suggest 216 for projectiles and dark gold - 164 for shootable static items ;)

**Comment by Zodomaniac** [comment]
I think I resolved the issue ;)
![DOOM0011](https://user-images.githubusercontent.com/15119473/59485710-82ebe800-8e7f-11e9-8089-7846c7592e50.png)
