### ISSUE TITLE
Sigil bug after beating level (non-compat or autoload)

### ISSUE THREAD

**Issue by buvk** [fabiangreffrath/crispy-doom#422]
When sigil is episode 5 (non-compat or autoload), when you beat a level (e.g. e5m8), the sound when the time and total time are tallied is played for too long.

This does not happen with the non-compat version when sigil is episode 3.

I suspect this has to do with par times (and the lack thereof).

**Comment by fabiangreffrath** [comment]
With "the sound" you mean the pistol sound and with "too long" you mean it is played although nothing is counted anymore on the screen?

**Comment by fabiangreffrath** [comment]
Alright, I think I see what you mean:

If SIGIL_COMPAT is loaded, the par times from episode 3 are used (although not displayed, because the map is loaded from a PWAD). Par time for E3M8 is 30 seconds. Since there are no par times for episode 5, the engine falls back to using the par times from Doom 2 *for the next map*. Par time for MAP09 is 270 seconds.

So, I assume you beat E5M8 in less than 270 seconds and thus the intermission screen keeps counting the par times, although they are not displayed, even after is finished counting your elapsed time for this map. I think I will just use episode 3's par times for episode 5, so the experience is at least the same.
