### ISSUE TITLE
[Question] Where is crispy-heretic crispness menu?

### ISSUE THREAD

**Issue by vanfanel** [fabiangreffrath/crispy-doom#512]
Hi there, @fabiangreffrath 

This question is pretty much self-explanatory. Is there no crispness menu for crispy-heretic? I mean, are crispness options supposed to work with crispy-heretic when forced on the CFG file anyway?
I am specially interested in uncapped framerate because, as you know, 35FPS looks BAD on todays ~60Hz displays...

**Comment by fabiangreffrath** [comment]
No, there is no Crispness menu in Heretic, because nobody implemented it yet. I never play Heretic, so someone else will have to take care of this. As for uncapped framerate, that's probably possible for Heretic as well, but - again - someone will have to implement frame interpolation, because I won't.

**Comment by JNechaevsky** [comment]
Oh yes, uncapped framerate is possible for Heretic, and even for Hexen (well, except for polyobjects - some extra job must be done). I'll just leave these examples here as a reference, but I can't let myself to make a PR in Crispy because of some possible code styling issues:

* Initial commit: https://github.com/JNechaevsky/russian-doom/commit/17a3d764cf2f3dd4d3e8dd9c460a69fc4009cb5d (there is also some unrelated mouse look code)
* Smooth texture scrolling: https://github.com/JNechaevsky/russian-doom/commit/bc7727da5b48f12d9e7cd67bd9c21217d7aab732
* Account vsync on/off for uncapped mode: https://github.com/JNechaevsky/russian-doom/commit/dcf9784599e49c93cf1da71b90654e4c687c7e0a

**Comment by fabiangreffrath** [comment]
> I can't let myself to make a PR in Crispy because of some possible code styling issues:

Erm, I am sure that we could get over this. Or have I been so cruel to you? :wink:

**Comment by JNechaevsky** [comment]
No-o, of course no, and never was! 

The problem is with different thing: you know how I'm writing or copying code, it's far different from your style, including formatting (i.e. replicating initial, original code) and often even far to be called "optimized", not good enough to be as good as yours.

Crispy Heretic is not a Russian Heretic, where I can do whatever I want. I have implemented a lot of various features, including gameplay features menu, and it's working fine. But - probably not fine enough in terms of code (not a visual) quality to be copied into Crispy.

I'm also having some problems with updating to your current code.

Thus, I'm a bit scary to proceed - I'm afraid to waste your time with finding out what can be possibly wrong in PR. 

And by the way, don't we have a focus on different thing now? :dog:

**Comment by fabiangreffrath** [comment]
> And by the way, don't we have a focus on different thing now? 🐶

No reason to neglect our beloved child Crispy. 😉  Whatever, I am always looking forward to your pull request, even if they affect Heretic. And we can always discuss style decisions, no contribution is bad per-se.
