### ISSUE TITLE
Inaccurate 16:9 display resolution

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#521]
### Background

Version of Crispy Doom: Latest git

Operating System and version: Win 7 Prof sp2

Game: Doom (2)
Any loaded WADs and mods (please include full command line):

### Bug description

Observed behavior: On a 1920x1080 monitor the screenshot resolution is 1920x1076 if `aspect_ratio_correct==1` and 1920x1078 if `aspect_ratio_correct==2`.

Expected behavior:  the display (and screenshot) resolution should be 1920x1080 regardless of aspect ratio correction.

**Comment by fabiangreffrath** [comment]
Well, the point is that there is some scaling and rounding of integer numbers in play. 

In hires mode the framebuffer height is 400 pixels. If aspect ratio correction is enabled this is blown up to 480 pixels. Divide this by 9 and multiply with 16 to get the desired framebuffer width. This is 853 pixels. Round this up to the next integer multiple of 4 which is 856.

Now scale this up to your screen's native resolution: 1920/856 = 2.243. Multiply this with the aspect ratio corrected height of 480 pixels and you'll receive 1076.

So, the culprit is that you start with a very limited framebuffer resolution which you blow up to match the screen resolution and have to consider integer math during the way.

**Comment by Zodomaniac** [comment]
>480 pixels. Divide this by 9 and multiply with 16

In the code you do `SCREENWIDTH = w * ah / h` i.e. first multiply, then divide, to obtain the 853 you mention.
I deem that for it should be rounded not to the upper but to lower multiple of 4, i.e. 852 which is closer to 853 than 856 is. Then 1920/852*480=1081.69~1082 which is closer to 1080 than 1076 is, and being above not below the vertical resolution of the monitor is better as it is trimmed away by the monitor itself when playing.

**Comment by fabiangreffrath** [comment]
It's not that easy. The height will be rounded down to 1081 by C's integer division. This wone pixel will not get trimmed away by the screen, but the 1081 will be scaled to fit into the 1080 pixels of your screen instead. This, in turn, will reduce your width away from 1920 pixels again. You can twist and turn it as you like, but you will never reach 1920x1080 with integer multiples of the original framebuffer size. :wink:

**Comment by Zodomaniac** [comment]
Alright, let's leave it as is.

**Comment by fabiangreffrath** [comment]
For the record, we will have to keep the framebuffer width at a multiple of 4 because SDL insists:

https://hg.libsdl.org/SDL/file/0d8343654eef/src/video/SDL_surface.c#l50

Pitch means the number of bytes that one horizontal row of pixels occupy in memory. And for a paletted framebuffer with only one byte per pixel this means we need to keep the number of pixels as a multiple of 4. Else, your screen will look messed up. Trust me, been there done that!

**Comment by Zodomaniac** [comment]
Thanks a lot for the explanation :)
