### ISSUE TITLE
Discoverability/familiarity of "A secret is revealed!"

### ISSUE THREAD

**Issue by oprypin** [fabiangreffrath/crispy-doom#526]
Hi!

There is this very widespread feature that pops up ["ᴀ ꜱᴇᴄʀᴇᴛ ɪꜱ ʀᴇᴠᴇᴀʟᴇᴅ!"](https://youtu.be/cgnG22K0Xq4) whenever a new secret area is found.

I (and apparently some other people around the internet) got so used to it that I assumed it was part of the original/vanilla Doom. From what I hear, it is present in almost all source ports.
I actually had assumed that Crispy Doom had a bug and was trying to identify it as a "regression" (and, well, this issue report started out very differently :joy:). I also felt that this detracted from my experience playing Doom without me realizing it at first. Was even starting to get a gaslighting kind of feel; at I first was sure that the effect doesn't trigger *only sometimes*.

It turns out that Crispy Doom actually has this feature, but with a few caveats:

1. It is hard to find. By that I mean... I had looked through the entire "crispness" menu at least 10 times, and every time I dismissed the relevant setting as being in the section about the minimap, which I didn't want to change.
2. You can enable it for both in-game and minimap, or neither. I would prefer to not have the minimap modified.
3. It is not enabled by default. Maybe it should be, if that's what many people expect. After all, Crispy Doom's defaults are not 100% vanilla.
4. The sound effect is different. I heard that this has to do with not using any sounds that aren't part of the original IWAD, while the most widespread sound *is* custom-made (originated, or at least definitely used, in ZDoom). Is this worth re-considering?

**Comment by Calinou** [comment]
> The sound effect is different. I heard that this has to do with not using any sounds that aren't part of the original IWAD, while the most widespread sound is custom-made (originated, or at least definitely used, in ZDoom). Is this worth re-considering?

Is there a sound present in IWADs that would be more suited? I think one of the design goals of Crispy Doom is to not require any additional resource to be usable.

**Comment by oprypin** [comment]
Well, if the sound is included as an audio file, it wouldn't exactly be an "additional" resource.

**Comment by oprypin** [comment]
To answer more directly, probably not; I don't expect that someone chose a sound that's not best suited.

Regardless, that point wasn't about what's best suited, but about having that exact sound effect. That would also make it more viable to enable by default.

**Comment by fabiangreffrath** [comment]
Hi,

> 1. It is hard to find. By that I mean... I had looked through the entire "crispness" menu at least 10 times, and every time I dismissed the relevant setting as being in the section about the minimap, which I didn't want to change.

That section isn't about the automap (it's not called minimap). Its section header reads "Navigational" which IMHO fits quite well: All the features listed here help with orientation in the map. In fact, only the first feature applies to the automap alone.

If you want to suggest a different name for the feature, I am all ears. How about "Report Revealed Secrets?" or "Show Revealed Secret Message?" or anything else?

> 2. You can enable it for both in-game and minimap, or neither. I would prefer to not have the minimap modified.

I have no idea what you are referring to here. If you enter a secret sector, the message is displayed. It makes no difference if you have the automap open at that time or not.

> 3. It is not enabled by default. Maybe it should be, if that's what many people expect. After all, Crispy Doom's defaults are not 100% vanilla.

Nope. Because if I change this now, four weeks later people will come and complain that the defaults are not Vanilla enough. I am not joking...

> 4. The sound effect is different. I heard that this has to do with not using any sounds that aren't part of the original IWAD, while the most widespread sound _is_ custom-made (originated, or at least definitely used, in ZDoom). Is this worth re-considering?

Nope. The "original" sound DSSECRET is not in Doom. If you want to hear it, you will have to provide it yourself (e.g. by loading prboom-plus.wad). If it is not available, a substitute sound will have to be played and the decision fell on one that isn't heard during regular game play.

> Well, if the sound is included as an audio file, it wouldn't exactly be an "additional" resource.

Please read through this sentence again.

I will not make Crispy depend on non-Doom resources, not in form of a mandatory `crispy-doom.wad` file nor by embedding lumps into the executable.

**Comment by fabiangreffrath** [comment]
> If you want to suggest a different name for the feature, I am all ears. How about "Report Revealed Secrets" or "Show Revealed Secret Message" or anything else?

How is the corresponding setting called in GZDoom? In PrBoom + it's called "SECRET AREAS". :thinking:

**Comment by oprypin** [comment]
> That section isn't about the automap

OK but every item in there affects the automap. Also "navigation" is associated with maps. Doesn't matter what you intend it to be, it's about appearances.

>> 2. You can enable it for both in-game and minimap, or neither. I would prefer to not have the minimap modified.
>
> I have no idea what you are referring to here. If you enter a secret sector, the message is displayed. It makes no difference if you have the automap open at that time or not.

Enabling the feature to pop up the message "A secret is revealed!" also controls this effect applying green color to the automap. Maybe I don't want it.

![automap](https://user-images.githubusercontent.com/371383/75402652-ae2b4000-5905-11ea-9137-7c0f074b05f1.png)

> Please read through this sentence again.

I do proof-read everything that I post, thank you very much.

> I will not make Crispy depend on non-Doom resources, not in form of a mandatory `crispy-doom.wad` file nor by embedding lumps into the executable.

Look, I get that this is the reason, but the reason itself doesn't seem to have any justification (maybe ideological?)
To point out the obvious, since it's neither of your examples, you could also ship a "secret.ogg" file with the game.

**Comment by oprypin** [comment]
> Enabling the feature to pop up the message "A secret is revealed!" also controls this effect applying green color to the automap. Maybe I don't want it.

Looks like disabling "Extended automap colors" is also preventing this green highlight, so I guess that combination of settings technically satisfies my wish, and it's fine for people wanting *that* to be vanilla.

---
In terms of renaming the feature, I couldn't come up with anything better but still concise.
Making it *first* in the section (so that the association with the automap doesn't set in yet) and named "Report Revealed Secrets" could be an improvement.

For reference, currently it's this:
![Navigational](https://user-images.githubusercontent.com/371383/75403325-a66c9b00-5907-11ea-9cd6-a958b3db6c8e.png)

**Comment by fabiangreffrath** [comment]
> OK but every item in there affects the automap. Also "navigation" is associated with maps. Doesn't matter what you intend it to be, it's about appearances.

Every item affects *also* the automap, but not *only* the automap. I still think that "navigation" is a fitting name for the section, because each feature in there is supposed to help with orientation on the game map. But let's please not slice up words here.

> Enabling the feature to pop up the message "A secret is revealed!" also controls this effect applying green color to the automap. Maybe I don't want it.

Ah, this! I remember that @Zodomaniac was very persistent to implement it and even provided the patch on his own. Yes, currently, if you don't like it you will have to disable the "Extended Automap Colors" feature.

You see, I am currently at a point where I would have to add a million switches for each and every microfeature. I hope it's understandable that I don't want this and so I decide to group similar features together by best conscience (that's e.g. why colored monster blood, spectre blood, Lost Soul blood puffs, colored marine corpses, etc. are combined into one feature). This approach cannot please everybody - it's impossible by principle. But I hope I can make clear how I believe some things simply belong together, e.g. if you want to get informed about secrets when you find them why wouldnt you want them highlighted on the automap?

> I do proof-read everything that I post, thank you very much.

Sorry, I didn't mean to sound rude but came around like that! Still, your sentence reads self-contradictory to me.

> Look, I get that this is the reason, but the reason itself doesn't seem to have any justification (maybe ideological?)
> To point out the obvious, since it's neither of your examples, you could also ship a "secret.ogg" file with the game.

The reason is a principle one. I never wanteds Crispy to depend on anything that's not provided by Doom itself or can be achieved by modifying its code. I don't want this to be one of the ports that need a PWAD to carry along in order to work. I know, things would be a lot easier if I would drop this principle - e.g. I could use other shapes than Doom's HU font characters for crosshairs, and I wouldn't have to code around the fact that TNTA0 is supposed to be an empty transparent sprite - but I have decided to go this way.

Anyway, the code is prepared for a DSSOUND sample lump, so you could just add this to a PWAD and load this at start-up (there is even an autoload feature available for this cases like this).

> In terms of renaming the feature, I couldn't come up with anything better but still concise.
> Making it _first_ in the section (so that the association with the automap doesn't set in yet) and named "Report Revealed Secrets" could be an improvement.

I don't think it's relevant enough to make it first in the list - and I still don't think it makes such a difference. If someone could tell me how the feature is called in GZDoom (I cannot - for unknown reasons - find it referenced in the sources) that would help.

To fix this bug, I will rename the feature in the Crispness menu. Until now "Report Revealed Secrets" is candidate #1. Further suggestions?

**Comment by fabiangreffrath** [comment]
@coelckers Could you please help me? How is the menu item called in GZDoom to enable/disable the "A secret is revealed" message and the playback of DSSECRET? I am somehow unable to locate it...

**Comment by coelckers** [comment]
CVAR(Bool, cl_showsecretmessage, true, CVAR_ARCHIVE) 

p_spec.cpp, line 573

**Comment by fabiangreffrath** [comment]
The menu string is "Show secret notifications" in GZDoom. @oprypin How would you like this one?

**Comment by oprypin** [comment]
Oh, that would be great! Although its effect on the automap is not represented.

**Comment by fabiangreffrath** [comment]
Indeed. So, for now we have

- Report Revealed Secrets
- Show Secret Notifications

Any other ideas? Could we probably have a poll on this?

**Comment by fabiangreffrath** [comment]
So, by now this little issue remains the only blocker for a 5.7.1 release. What should I do?

**Comment by oprypin** [comment]
Probably release 5.7.1,
cuz why not

**Comment by fabiangreffrath** [comment]
> cuz why not

Because this is such a low-hanging fruit and I'd like to have it fixed ASAP. 

We need to improve the discoverability of the "A Secret is Revealed" feature - you have convinced me of that - but I am still unsure which is the best name for the menu switch. I'd go with GZDoom's "Show Secret Notifications", but this doesn't take the automap highlighting into account. The other alternative "Report Revealed Secrets" covers that better (highlighting an area on a map may be considered as some kind of reporting) but is still very close to what we have now.

Anyway, I think I'll change it to the latter and be done with it. @Zodomaniac would you please update the README document with the changelog? Should be rather easy this time. :grin:

**Comment by Zodomaniac** [comment]
@fabiangreffrath , the changelog is done, with this change included. I agree the item should be called 'Report revealed secrets'.

**Comment by Zodomaniac** [comment]
>Enabling the feature to pop up the message "A secret is revealed!" also controls this effect applying green color to the automap. Maybe I don't want it.

@oprypin, thanks for inspiring me to add another variable and menu item to So Doom :)
