### ISSUE TITLE
Inconsistent handling of menus with joystick control

### ISSUE THREAD

**Issue by forgeflow** [fabiangreffrath/crispy-doom#55]
Using crispy-doom with a gamepad controller allows for the use of the DOOM menu using the Y-axis control for up-down, and fire button for selection. However, neither crispy-heretic nor crispy-hexen work in the same way, even though the setup and config files for each of these games are nearly identical.

**Comment by fabiangreffrath** [comment]
I agree and have to admit that there is a lot of inconsistency between Crispy Doom and its neglected stepbrothers. ;) However, I am sure that in this specific case, the inconsistency in menu control with a gamepad is already present in the Chocolate ports of the games. Since I am not going to deviate from Crispy's upstream in this regard, it will probably make more sense to take this issue there.

**Comment by fabiangreffrath** [comment]
I consider this an upstream bug that should get fixed in Choco first and then migrate to Crispy. Please feel free to check this behaviour in a recent SDL2-based Choco snapshot and report a bug there if you feel something is still missing.
