### ISSUE TITLE
add prboom+/zdoom style widescreen HUD

### ISSUE THREAD

**Issue by sovietmewtwo** [fabiangreffrath/crispy-doom#553]
i love the new widescreen feature of crispy doom, but i don't really like the transparent HUDs. i think that it'd be a good idea to add a widescreen HUD similar to the ports mentioned in the title, with the brick patterns to the side. thank you

**Comment by Zodomaniac** [comment]
I'd suggest not bricks byt the face background section of `STBAR` repeated to fill the sides via `V_CopyRect()`

**Comment by Zodomaniac** [comment]
Alas. my design decision looks bad with some status bars, e.g. with the one from Eternal Doom:
![DOOM0072](https://user-images.githubusercontent.com/15119473/77515712-15e39500-6e8a-11ea-8a97-54e280adca73.png)
so I'll have to adapt the code from PrBoom+

**Comment by fabiangreffrath** [comment]
I don't think this even needs a single line of PrBoom+'s code, actually.

**Comment by JNechaevsky** [comment]
From my short experience, two thing are needed for such border drawing.

1) A `for` vector which will draw bezels (`V_DrawPatch`). Nothing special, it's ex termly easy.
2) A `for` vector which will draw background from RAW Doom flat. The problem is - there is no `Y` coordinate for drawing function, so some additional code must be written to draw background not for top `Y` coord (`0`), but starting from status bar height. I have no idea how to do this.

**Comment by Zodomaniac** [comment]
Done in https://github.com/fabiangreffrath/crispy-doom/commit/11beaaed2adda01537508e8e1836070dca18740b.
![DOOM0093](https://user-images.githubusercontent.com/15119473/78043805-7e47e000-737c-11ea-8183-54b0f59d65b1.png)
