### ISSUE TITLE
Widescreen statusbar sometimes duplicates numbers in automap

### ISSUE THREAD

**Issue by kitchen-ace** [fabiangreffrath/crispy-doom#594]
### Background

Version of Crispy Doom: 5.8.0

Operating System and version: Arch Linux 64-bit

Game: Doom

When cycling through the different widened extended statusbar/HUD modes with +, and then going to the automap, you can get duplicate numbers as in the screenshot below. This doesn't seem to *always* happen though, I can't figure out a consistent way to reproduce it, but it should be easy enough to repro by pressing tab after changing the HUD mode a few times.

nb: this was discovered as part of a test for [this post](https://www.doomworld.com/forum/post/2119013) on DoomWorld; if you were to implement a no-HUD automap it should maybe be done before fixing this bug (but also maybe not).

![DOOM0000](https://user-images.githubusercontent.com/47063032/80142239-d7b8be80-8578-11ea-96da-e0f16297163e.png)

**Comment by fabiangreffrath** [comment]
This only happens with "Uncapped Framerate" enabled, right?

**Comment by kitchen-ace** [comment]
Seems like that's right.

**Comment by fabiangreffrath** [comment]
So, the general logic seems to be correct, but there is still a racing condition between the engine "knowing" that it has to draw the brick background for the status bar because of the automap - but still not having realized that the automap requires the narrow widget alignment. I guess I'll have to move the check for this from the thinker function into the drawer function.
