### ISSUE TITLE
Segfault on IMMLEV.WAD E2M1

### ISSUE THREAD

**Issue by tpoppins** [fabiangreffrath/crispy-doom#621]
IMMLEV.WAD from [immbeta2.zip](https://www.doomworld.com/idgames/levels/doom/g-i/immbeta2)
Today's daily Crispy build
Win 7 Pro x64 SP1

```
                           Crispy Doom 5.8.0
Z_Init: Init zone memory allocation daemon.
zone memory: 024A0020, 32 MiB allocated for zone
V_Init: allocate screens.
M_LoadDefaults: Load system defaults.
saving config in default.cfg
W_Init: Init WADfiles.
 adding doom.wad
 merging C:/WADS/idgames/WAD/immbeta2/IMMLEV.WAD !
  loaded 0 DEHACKED lumps from PWAD files.
===========================================================================
                           The Ultimate DOOM
===========================================================================
 Crispy Doom is free software, covered by the GNU General Public
 License.  There is NO warranty; not even for MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE. You are welcome to change and distribute
 copies under certain conditions. See the source for more information.
===========================================================================
I_Init: Setting up machine state.
OPL_Init: Using driver 'SDL'.
NET_Init: Init network subsystem.
M_Init: Init miscellaneous info.
R_Init: Init DOOM refresh daemon - ...........................
P_Init: Init Playloop state.
S_Init: Setting up sound.
I_SDL_PrecacheSounds: Precaching all sound effects......................Segmentation fault
```

prboom-plus v2.5.1.4 crashes with this in stdout.txt:
```
P_GetNodesVersion: using normal BSP nodes
P_LoadSegs: seg 1617 references a non-existent linedef 65535
```

Vanilla  (UD under Dosbox) crashes on this map about four times out of five with 

`P_CrossSubsector: ss 15805 with numss = 545`

(or some other number instead of 15805) but every now and then allows you to proceed, although the map appears to be broken in more than one way and unfinishable. Ah, and it is also a slap-dash edit of a tutorial WAD stolen from the 3D Alchemy book with not a word of acknowledgement, but that's just an aside.

The punchline is that today's daily Choco build loads this map with no error every time, and you can play until you get stuck due to other errors in the design. Ditto for v3.0.0. A cute little puzzle. Would it qualify as an upstream issue? :)

**Comment by fabiangreffrath** [comment]
Without having had a look at the map nor at the code: The value `65535` is `0xffff` and thus `-1` for a signed short type variable, but `65535` for unsigned short or int type variables. Since both PrBoom+ and Crispy support maps in "extended nodes" formats, they have some internal variable types changed  from signed short to either unsigned short or int. Chocolate doesn't have this change.

This means that some seg is supposed to refer to linedef `-1` in this map, which means that some array is going to underflow by one entry in Vanilla and Choco. That same value will also cause an overflow by some very large number in PrBoom+ and Crispy, though. It is wrong either way.

The effect of the underflow may be strictly undefined and depend on the actual memory layout of the executable, which is why Vanilla survives it sometimes and Choco survives it each time - by pure incident.

**Comment by fabiangreffrath** [comment]
I fixed this by gracefully exiting with an error messages just as PrBoom+ does. The reason is that I cannot leave the linedef as-is, because I use it later to calculate the texture offset for the seg and this simply will not work for `&lines[-1]`.

**Comment by tpoppins** [comment]
Thank you for the explanation, Fabian.
