### ISSUE TITLE
Final DOOM as PWAD oddities

### ISSUE THREAD

**Issue by tpoppins** [fabiangreffrath/crispy-doom#626]
Loading Final DOOM IWADs as PWADs (i.e. `crispy-doom -iwad doom2.wad -file tnt.wad` or `crispy-doom -iwad doom2.wad -file plutonia.wad`) produces strange results:

1) RSKY1 is the starry sky Crispy uses for the Master Levels (found via %DOOMWADDIR%) - cf. #627.
2) RSKY2 and RSKY2 are from DOOM2.
3) The three episodes listed under the New Game/Which Episode? menu use the names of the first three episodes of DOOM.WAD. Starting "Knee Deep in the Dead" gives TNT or Plutonia (depending on which one is "-file"d, "Shores of Hell" - NRFTL, "Inferno" - Master Levels.

Using `-gameversion final` makes no difference.

**Comment by fabiangreffrath** [comment]
1. The Final Doom IWADs are supposed to be loaded as IWADs, i.e. there is no code in Crispy (or any other source port that I know of) that detects them being loaded as PWADs and applies some special treatment.
2. The sky rendering issues are caused by the Master Levels PWADs being audo-loaded and overriding the sky textures and overriding the TEXTURE1 and PNAMES lumps.
3. For unknown reasons, each Doom 2 / Final Doom IWAD contains the menu graphics lumps for Doom 1's episode selection. Only in the BFG Edition IWAD for Doom 2 these have been corrected to read the actual "Hell On Earth" / "No Rest For The Living" episode names. Thus, the episode selection menu is only rendered with these graphics, if the IWAD is detected to be the one from the BFG Edition. 
  However, it must be possible to also provide these graphics lumps by loading a PWAD, so the logic is to render the episode selection menu with the graphics lumps if these lumps are (1) either from the BFG Edition IWAD or (2) from a PWAD. And since you load the Final Doom IWADs as PWADs and since these do contain the episode selection graphics lumps (albeit showing the Doom 1 episode names) the menu is rendered with these lumps.

**Comment by tpoppins** [comment]
Moral: don't load IWADs as PWADs!

Thank you for the explanation, fabian.
