### ISSUE TITLE
Error loading wad with missing patches

### ISSUE THREAD

**Issue by kitchen-ace** [fabiangreffrath/crispy-doom#646]
### Background

Version of Crispy Doom: latest git build

Game: Doom 2 

Any loaded WADs and mods (please include full command line): crispy-doom -file reticue1.wad

Available at https://www.doomworld.com/files/file/17401-reticula-episode-1/

Trying to load this wad in Crispy fails. It loads fine in both Chocolate Doom and PrBoom+.

The TEXTURE1 and PNAMES entries are a bit of a mess: There are textures with empty sections, patches in PNAMES that don't exist, no DBRAIN1 texture but DBRAIN2-4, etc. Nonetheless it loads just fine in Chocolate and others.

error message:

    R_Init: Init DOOM refresh daemon - [                                            
    .................R_GenerateLookup: column without a patch (BIGDOORA)
    R_GenerateLookup: column without a patch (DOOR4)
    R_GenerateLookup: column without a patch (DOOR6)
    R_GenerateLookup: column without a patch (TUSC02)
    R_GenerateLookup: column without a patch (TUSC04)
    R_GenerateLookup: column without a patch (TUSC06A)
    R_GenerateLookup: column without a patch (TUSC06B)
    .........................!......
    P_Init: Init Playloop state.
    P_InitPicAnims: bad cycle from DBRAIN1 to DBRAIN4

**Comment by fabiangreffrath** [comment]
This is probably because Crispy tries to take entried from all available PNAMES and TEXTURE1/2 lumps into account.

Not sure how to get out of this, though. I'll probably have to check if taking the offeding texture out of the animation loop fixes the issue and then proceed with it.

**Comment by fabiangreffrath** [comment]
Choco et al. got away with it, because if the DBRAIN1 texture (i.e. `startname` in this cycle) is missing from the TEXTURE1 definition lump, so the engine cannot find it and skips the entire sequence (check for the "`// different episode ?`" comment in `P_InitPicAnims()`). In Crispy, however, we still know about this texture from the IWAD's TEXTURE1 lump and will thus still try to construct the cycle. 

I have modified the check to merely skip the animation sequence if a byd cycle is detected instead of erroring out. IMHO, this comes closest to Vanilla behaviour while keeping the texture index merging feature intact.
