### ISSUE TITLE
Xbox Controller Trigger

### ISSUE THREAD

**Issue by Marscaleb** [fabiangreffrath/crispy-doom#65]
I am trying to play with an Xbox 360 controller (specifically, the "Rock Candy Gamepad for Xbox 360") and I cannot assign the triggers to work as buttons.

**Comment by fabiangreffrath** [comment]
Hi,

thank you for your bug report!

AFAICT, the triggers on XBOX controllers are treated as axes instead of regular buttons and both Chocolate Doom and Crispy Doom currently lack proper support for this. Since Crispy Doom shares the input handling with Chocolate Doom nearly unmodified, I think it would be better to solve the problem upstream. There is already a bug opened on the Chocolate Doom issue tracker, so there isn't much I am going to add here:

https://github.com/chocolate-doom/chocolate-doom/issues/424

**Comment by fabiangreffrath** [comment]
This should be fixed upstream in the Chocolate Doom project and then merged into Crispy Doom.
