### ISSUE TITLE
Issues when loading widescreen status bars in two different ways

### ISSUE THREAD

**Issue by ghost** [fabiangreffrath/crispy-doom#665]
Version of Crispy Doom: 5.9.0

Operating System and version: Windows 10 Pro 1909

Game: Doom (possibly happens in other games)

Any loaded WADs and mods (please include full command line): crispy-doom -iwad DOOM.wad -file doom_wide.wad (mod can be found here [https://forum.zdoom.org/viewtopic.php?f=19&t=37960](url))

### Bug description

Observed behavior: While using widescreen status bar wads by loading them with command line arguments, the game crashes while attempting to load a level. Using the setup tool to load the wads worked perfectly, but with minor graphical bugs on the right side of the status bar.

Expected behavior: The game should not crash while loading widescreen status bars with command line arguments and should display the status bar correctly when loading with the setup tool

![image](https://user-images.githubusercontent.com/24397028/92631421-9f204400-f2d1-11ea-916c-8d80e130f19d.png)

**Comment by fabiangreffrath** [comment]
The widescreen status bars are quite obviously mods targeted at ZDoom. Why do you believe they would work without further modifications in a stricly Vanilla-compatible port like Crispy?

**Comment by drfrag666** [comment]
The new Unity iwads also contain a wide status bar and it looks bad, do you plan to support those?

**Comment by drfrag666** [comment]
Yeah i've just checked with a pwad including the assets Kinsie provided, the titlepic also looks bad.
Those assets can be distributed for non commercial use.
[unityassets.zip](https://github.com/fabiangreffrath/crispy-doom/files/5210332/unityassets.zip)

**Comment by sponge** [comment]
I can provide a little info on how the widescreen lumps work in the official ports if you wish to support them, it's a very simple solution since I was dealing with basically vanilla UI code.

I basically split up DrawPatch into two functions, DrawPatch and DrawPatchLeft. Calling DrawPatch will add an offset based on the (in our case, hardcoded) screen width, such that x = 0 is the left side of an invisible 4:3 screen centered inside. Anything that is widescreen aware will call DrawPatchLeft where x = 0 is the left side of the framebuffer. You probably already have a solution to this since Crispy already has great widescreen support, but we absolutely didn't.

From there, for any of the fullscreen lumps (TITLEPIC, CREDIT, HELP, STBAR, and a couple of others that escape me) are just drawn with an offset to keep them centered based on the lump width. In our case, we're hardcoded to 426 width, but x is calculated with `(screen_width - lump_width) / 2`. No weird metadata lumps or extended formats needed, and it still will render the 1.9 IWADs (and all mods) perfectly fine. Our source port can't start drawing from -x DrawPatch values, but if you skip negative x columns, this will also correctly render 16:9 lumps when running in 4:3 (or 16:10 and so on). None of the official art is designed with any important info in the 16:9 sections.

The only other slightly tricky one was the bunny ending. PFUB2 is 426 wide, but PFUB1 is still 320, so the scrolling is still 320 pixels, enough to scroll PFUB1 off the screen.

I'd love if the new widescreen lumps ended up getting supported in other mods, but I understand if it's considered too-not-vanilla.

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/crispy-doom/commit/a243b66e46f1e1492ffc20f61967968caa764d55
