### ISSUE TITLE
[Question] Crispy Hexen and Strife?

### ISSUE THREAD

**Issue by Mechanical-sanity** [fabiangreffrath/crispy-doom#785]
So a while back, things seemed pretty set in stone, until crispy heretic was released early last year, and I was wondering if that meant hope for a crispy hexen and crispy strife? I know it would be a lot of work, but I was just asking, since strife especially needs some good source ports.

**Comment by fabiangreffrath** [comment]
Both games are kept in a working state can can be built manually from the sources. However, they are not built by default and not part of the official releases, because I don't want to raise any expectations that they are actively developed or that anyone even actually cares about them. Heretic has been promoted in the past, because if has seen massive development by contributors and is at least partly on par with Crispy Doom now. Until something like that happens to Hexen and/or Strife, these two games are going to stay where they are.

**Comment by Mechanical-sanity** [comment]
Shame. Oh well
