### ISSUE TITLE
Netgame broken in Crispy Doom 3.1 and further, including daily latest builds

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#80]
When launching a netgame, the game window appears only for hosting player, and it's completely black for about half a minute. After this the hosting player appears in game, but the in-game messages say other players have left the game. The stdout file reads that all clients but the local one are dropped on timeout. Many measures have been attempted to fix this bug or at least track it down but they all failed:
1) Replacing the SDL *dll-s with ones from Crispy 3.0
2) Launching netgame with -nodeh command line parameter
3) Chocolate Doom 2.2.1 client plays successfully on Crispy 3.2 server, but the Crispy 3.2 client fails to
4) Running the executables as admin

**Comment by Danfun64** [comment]
Probably not helpful, but I've had this issue as well.

**Comment by Danfun64** [comment]
Well, I think I found the cause to this bug. #82.

**Comment by fabiangreffrath** [comment]
Thank you incredibly much @Danfun64 for investigating and even fixing this issue!

However, I hope you understand that I don't want to rip out this feature entirely. So, could you please check if
a) either removing `W_ReleaseLumpName("STFB0");` fixes the issue (I fear not)
or
b) adding `&& demoplayback` to the `if (...)` condition fixes the issue?

Thank you very much already!

In related news, I have a new computer since this week and it even has Windows 10 pre-installed, so I might be able again to fix issues like this in the shorter term from now on. I currently do not have a development system (i.e. MSYS2 and MinGW) set up on it though, so a new release will take some time. Meanwhile, I'd like to ask you to use the daily builds provided at this site:
http://latest.chocolate-doom.org/

Thanks again,

Fabian
