### ISSUE TITLE
Where the command-line arguments are documented?

### ISSUE THREAD

**Issue by 07416** [fabiangreffrath/crispy-doom#828]
The *new* Crispy Doom arguments are [in the Github readme](https://github.com/fabiangreffrath/crispy-doom#new-command-line-parameters) the Chocolate Doom ones can be found from [the respective website](https://www.chocolate-doom.org/wiki/index.php/Command_line_arguments), but does this fully cover the available and supported commands?

For instance, I don't know if the rendered (background) gameplay in the main menu can be disabled.

**Comment by fabiangreffrath** [comment]
No, the background menu can't be changed.

Documentation is always an issue, because nobody likes to write it. I am glad that we have at least documented the parameters added relative to Chocolate Doom at some point. If you are familiar with the code, you could still search for occurances of `M_CheckParm()` and `M_CheckParmWithArgs()`.

@FozzeY Your PR #796 adds a lot of new parameters. Could you please complete this with adding these commands to the README document? The "new since" version will be 5.11, thanks!

**Comment by fabiangreffrath** [comment]
I think now we have all new command line parameters documented.
