### ISSUE TITLE
Modern Controller Support?

### ISSUE THREAD

**Issue by OpenRift412** [fabiangreffrath/crispy-doom#829]
Could we perhaps get a more expanded implementation of controller support, akin to what we've seen in Woof (twin-stick, finer analog control, etc.)? 

Also, I've noticed that the latest build from the chocolate doom autobuilds page doesn't seem to detect my Xbox controller at all, so you may want to look into that as well.

**Comment by fabiangreffrath** [comment]
> Could we perhaps get a more expanded implementation of controller support, akin to what we've seen in Woof (twin-stick, finer analog control, etc.)?

Yay, no week shall pass without someone requesting controller support. 😉 No, seriously, this is requested over and over again and I usually send people over to the Chocolate Doom issue tracker, because the whole input handling is inherited from Choco and proper controller support shouldn't be a Crispy specific change. However, there are already a couple requests there and even an unfinished PR and adding even more duplicates just won't help. It seems that none of us devs ever plays with a controller, so if people want controller support, they will need to find someone who adds it for them or do the grunt work themselves. (I am not saying that you should, I am just saying that I won't).

> Also, I've noticed that the latest build from the chocolate doom autobuilds page doesn't seem to detect my Xbox controller at all, so you may want to look into that as well.

The autobuild server is not under my control. The issue seems to be that it still uses a severely outdated version of SDL, but upgrading to a newer release will require an updated build tool chain as well:

https://github.com/chocolate-doom/chocpkg/issues/21

**Comment by OpenRift412** [comment]
Oh, whoops, sorry...

**Comment by fabiangreffrath** [comment]
No need to apologize! 😉
