### ISSUE TITLE
-statdump doesn't produce results for E1M8 (boss levels)

### ISSUE THREAD

**Issue by pepperpow** [fabiangreffrath/crispy-doom#846]
### Background

Version of Crispy Doom:
5.11.1

Operating System and version:
OS Name	Microsoft Windows 10 Pro
Version	10.0.19043 Build 19043

Game: (Doom/Heretic/Hexen/Strife/other)
Doom Ultimate

Any loaded WADs and mods (please include full command line):
`crispy-doom.exe -statdump run.txt`

### Bug description

Observed behavior:
Upon reaching the end and completing E1M8 (through idclev08 and idclip), a stat screen is shown and calculated, and an ending screen appears.  The resulting txt file `run.txt` has no statistics printed.

Expected behavior:
Regardless of completion (E1M1 still prints out with above conditions), it should do a statdump for ending levels.

**Comment by fabiangreffrath** [comment]
Originally, `-statdump` data was only generated during the intermission screen - and neither Vanilla nor Chocolate Doom show such a screen after ExM8. However, since the main purpose of the statdump feature is to compare its output to Vanilla and Chocolate Doom to make sure demos keep sync, I had to adapt the code accordingly.

If you are looking for a more detailled stats output for your runs, check out the `-levelstat` parameter.

**Comment by pepperpow** [comment]
Just realized I was looking in cmdline.html instead of the readme for any more info.  Thank you
