### ISSUE TITLE
Saving and loading in demos

### ISSUE THREAD

**Issue by plumsinus** [fabiangreffrath/crispy-doom#86]
If you quicksave while recording a demo, the first instance where the save menu is brought up, the game pauses, which is good. After that though, when you get the "Quicksave over your game" prompt after trying to quicksave again, the game does not pause, causing a desync unless the player pauses manually.

Quickloading (or normal loading) should be disabled entirely while recording. As of right now you can load a game while recording, which of course causes a desync. (You can save while recording a demo and then load from the saves once you are not recording, so there is a point to keeping quicksaving while demo recording.)

PrBoom+ gives you a message along the lines of "can't quickload during a demo!", but even doing nothing when trying to load a game is preferable to a desync.

**Comment by fabiangreffrath** [comment]
I see what you mean, the code is in doom/m_menu.c. I could either re-use the strings that are displayed when trying to load a game during a netgame (LOADNET/QLOADNET in doom/d_englsh.h) or invent a separate pair of strings. What do you think?

**Comment by plumsinus** [comment]
Well I'm fine with the existing strings but it might look a little better to have new ones. Perhaps "You can't (quick)load during a demo!" ?

**Comment by plumsinus** [comment]
Also it might be better just to display the message in the top-left of the screen, same area as notifications for picking up things, rather than having to do another pause to display a centred message. I will leave this decision up to you though.

**Comment by fabiangreffrath** [comment]
I appreciate your advice, thank you!

> Perhaps "You can't (quick)load during a demo!" ?

Don't forget "You can't start a new game while recording a demo". These three could be condensed into a generic "You can't do this while recording a demo" warning, though.

However, I think it will be better not to display any message at all and simply ignore the key press. As they currently are, I agree, the messages are plain wrong and misleading and they interrupt the game for no good reason. The top-left message bar is strictly reserved for in-game notifications (not technical details and engine limitations) and I'd like to leave it that way for consistency.

What I still want to achieve is to automatically un-pause the game after either canceling or confirming the quick-save.

**Comment by plumsinus** [comment]
> I think it will be better not to display any message at all and simply ignore the key press.

Sure, you have listed some good reasons for that and I think it's fine that way. I don't know if selecting Load Game from the menu is a separate case, but if it is it's probably fine to just do nothing for that too.

Just to be a smart-ass though: Low Detail/High Detail messages do appear in the top-left bar :p

**Comment by fabiangreffrath** [comment]
> Sure, you have listed some good reasons for that and I think it's fine that way. 

I think I'll let it play the "oof" sound as an audible feedback. Yes, and I will disable the Load Game entry from the main menu if a demo is recorded.

> Just to be a smart-ass though: Low Detail/High Detail messages do appear in the top-left bar

And so is the Screenshot message, but these are confirmations for purposeful user action, not warnings or error messages. ;)

**Comment by fabiangreffrath** [comment]
I think this issue is mostly resolved now with the latest commits pushed to the repo. Daily snapshots are available here: http://latest.chocolate-doom.org/

What is still missing is to automatically un-pause when a game is saved or a message is confirmed. The problem in these cases is the following block of code in `D_ProcessEvents()`:
```
    while ((ev = D_PopEvent()) != NULL)
    {
	if (M_Responder (ev))
	    continue;               // menu ate the event
	G_Responder (ev);
    }
```

When the player confirms the name for the savegame or presses a key to close an in.game message (e.g. press F7 to end the game, press 'n' to continue) then `M_Responder()` "eats" this keypress and returns `true`. Thus, the `while` loop skips the call to `G_Responder()` which in turn is responsible for pausing/un-pausing the game. This means we need another keypress to make `D_PopEvent()` return another event that is *not* eaten by `M_Responder()` and thus passes on to `G_Responder()` which then finally unpauses the game.

Im am not sure yet how to fix this, but I am afraid it will be tricky. Don't expect anything too soon yet.

**Comment by fabiangreffrath** [comment]
@plumsinus Please close this issue if appropriate.

**Comment by plumsinus** [comment]
I think this covers everything (other than unpausing automatically).
