### ISSUE TITLE
Automap lines get drawn unaliased in stretched video modes, losing colours

### ISSUE THREAD

**Issue by plumsinus** [fabiangreffrath/crispy-doom#89]
I don't know if this is the right terminology, or if this is something fixable.

When I play in a video mode other than a multiple of 640x480, the lines drawn on the automap seem to have some kind of anti-aliasing going on where certain segments of lines are drawn in a darker colour. This isn't too bad for normal lines but with certain lines like yellow key doors, they lose their colour if the automap is in the wrong place or zoom level. Some lines are drawn fatter than others as well. Perfectly horizontal lines are unaffected. 

I don't notice the same thing in Chocolate Doom, though the difference in resolution might have something to do with that.

**Comment by fabiangreffrath** [comment]
Yes, this happens because the lines in the automap need to get stretched by factor 1.2 vertically and the resulting interpolated color must still be found in Doom's palette. This comes along with visible artifacts for some colors.

Things will get better when the screen is scaled and stretched by actual hardware rendering which will be possible as soon as Choco's sdl2-branch has been merged.

**Comment by plumsinus** [comment]
That is what I suspected. Oh well, playing in 640x480 works for the time being.

**Comment by fabiangreffrath** [comment]
This has been brought up on DW again, so maybe I should find better suited colors in the short term.
