### ISSUE TITLE
[Hexen] Second internal demo desyncs

### ISSUE THREAD

**Issue by rzhxiii** [fabiangreffrath/crispy-doom#893]
### Background

Version of Crispy Doom: built from commit e89cc04

Operating System and version: Windows 10 (32 bit)

Game: Hexen

Any loaded WADs and mods (please include full command line): N/a (this happens even without any loaded WADs)

### Bug description

Observed behavior: the second internal demo (Mage on Guardian of Fire) desyncs in latest versions. This does not happen in either the latest stable release of Crispy Hexen or in latest builds of Chocolate Hexen.

This happens even with a fully vanilla set-up (no Crispy settings enabled, vertical mouse movement turned on, etc.)

Expected behavior: I haven't managed to track down the culprit yet, but hopefully it can be found soon. I'll have more time available tomorrow and on Friday so hopefully I can test this further then if required.

**Comment by fabiangreffrath** [comment]
Hm, does this demo involve polyobj movement?

**Comment by turol** [comment]
Can you use git bisect?

**Comment by mikeday0** [comment]
I'm guessing this is my fault. :) I suspect the issue arises due to the new mouselook code, which was introduced in 9ab1e67e. I don't think I applied the MLOOKUNIT factor everywhere that I needed to.

I have been preparing a follow-up PR for mouselook on the `hhmouselook2` branch which I think has some changes which might fix this. Can you check the latest commit on that branch? 063839ca

**Comment by fabiangreffrath** [comment]
Could you please file a PR for that branch?

**Comment by fabiangreffrath** [comment]
Yes, seems fixed now!

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/crispy-doom/commit/83d50fc19e69abb530bfcfbee7a01107b6f8027c
