### ISSUE TITLE
Blood of players with Invulnerability/IDDQD to be replaced with bullet puffs

### ISSUE THREAD

**Issue by Zodomaniac** [fabiangreffrath/crispy-doom#90]
Initially my idea was that invulnerable players shouldn't bleed at all, but as it's impossible because of blood splats being map objects, I'd suggest them to become white if the player has invulnerability artifact/IDDQD cheat on (like invulnerability super-armor crumbles). Thus if in the deathmatch one sees somebody bleed white, RUN, FORREST, RUN!111

**Comment by fabiangreffrath** [comment]
> I'd suggest them to become white if the player has invulnerability artifact/IDDQD cheat on

I agree that this would fit pretty well with the visual appearance of the colorized status bar numbers.

> Thus if in the deathmatch one sees somebody bleed white, RUN, FORREST, RUN!111

But wouldn't it be an unfair advantage of the player being attacked to find out immediately that his opponent is invulnerable?

**Comment by Zodomaniac** [comment]
I think that vice versa, the impossibility to detect the opponent's invulnerability is unfair.
Another idea I had is: is it possible to replace the blood splat sprites for invul players with bullet puff sprites? as for bullets the invulnerable player is the same as a wall.

**Comment by fabiangreffrath** [comment]
I just had this very same idea as well. Let's see...

**Comment by Zodomaniac** [comment]
I remembered one more thing: there is a Crispness option fixing Lost Soul blood. When I shoot Lost Souls, there is no blood at all, so how have you fixed it?

**Comment by fabiangreffrath** [comment]
It's called "Fix Spectre and Lost Soul Blood" and actually Lost Souls "bleed" puffs if enabled.

**Comment by Zodomaniac** [comment]
>actually Lost Souls "bleed" puffs if enabled.

This is well done! :+1:

**Comment by Zodomaniac** [comment]
Invulnerability gives the player access to the most powerful weapons and powerups as no one can stand in his way, so enabling the 'invulnerability detection' is a nice balancing feature IMO.

**Comment by plumsinus** [comment]
Crispy Doom is multiplayer-compatible with Chocolate Doom, right? (And other ports too??)

If so, then an advantage that a player gets from using Crispy Doom in multiplayer, regardless of your feelings on invulnerability balance, would probably be considered a cheat by players. 

I don't really play multiplayer but I don't think this would be well received by people that do. You should probably consult with other people who play multiplayer before implementing this, unless it's limited to Crispy Doom-only multiplayer games.

**Comment by Zodomaniac** [comment]
>If so, then an advantage that a player gets from using Crispy Doom in multiplayer, regardless of your feelings on invulnerability balance, would probably be considered a cheat by players.

Yes, Crispy Doom is compatible with Choco, but already has some client-side enhancements, e.g. Crispy Doom has mouselook which is useful to look up/down steep stairs to see a possible enemy there. So I'll be fine with this enhancement as well)

**Comment by fabiangreffrath** [comment]
Hey guys,

thank you for discussing this issue!

I have slept a night over it and I think @plumsinus is right: This request is more than a graphical gimmick, it is a tactical advantage for the opponent. As much as I understand our concern, @Zodomaniac , but "balancing multiplayer deathmatch" is certainly not Crispy's goal .

And it shouldn't be. As has already been pointed out, multiplayer compatibility with Choco is the main issue here. I agree that Crispy already has some features that could mean an advantage for the player using it (e.g. projected crosshair or vertical free look, although you cannot shoot where you look in multiplayer games) and maybe it has even gone a bit too far with that already. That's why any further enhancement need to be considered carefully.

So, I think telling one player that the other one has some specific power-up in a deathmatch game goes a bit too far. Sorry, but I'll mark this as "wontfix" for now. :/

**Comment by fabiangreffrath** [comment]
I am closing some old issues that I consider irrelevant by now. Feel free to reopen with a comment if you disagree.
