### ISSUE TITLE
Toggle for map33 behavior.

### ISSUE THREAD

**Issue by Danfun64** [fabiangreffrath/crispy-doom#91]
It would be nice if there was an option to change how map33 is loaded. This mainly concerns D2TWID.

Option 1: Access to map33 through normal gameplay is disabled. Accessing the secret exit sends you back to map01 ala PrBoom-Plus with doom2.wad as iwad.

Option 2: Access to map33 through normal gameplay is granted, but all SS are replaced with zombiemen ala PrBoom-Plus with bfgdoom2.wad as iwad.

Option 3: Access to map33 through normal gameplay is granted, and SS appear as usual. Basically what the setting is now, which for some reason doesn't exist in PrBoom-Plus.

It would make demo accuracy easier.

**Comment by plumsinus** [comment]
Hm, I must admit that when I suggested the feature to always go to MAP33 if it exists I didn't consider the option of people intentionally hitting the secret level switch on MAP02 to go back to MAP01. Do actual demos that do this exist? 

I know fabian is not fond of extra options, perhaps it is best to just revert this feature and change the behaviour of MAP02->MAP33 based on the use of the BFG iwad. (I agree that this feature makes sense for PrBoom+ which is full of compatibility options.)

**Comment by fabiangreffrath** [comment]
Hey guys,

thank you for discussing this issue!

However, I don't understand the problem here.

1) Access to map33 from the secret exit in map02 is *only* available in single-player games, not in network games or while recording or playing back a demo. In the latter cases, Crispy will behave exactly like DOOM2.EXE (or PrBoom-Plus, that is).

2) SS are replaced by zombiemen *only* in single-player games *and* if the IWAD is detected as DOOM2.WAD from the BFG Edition. During network games and while recording or playing back a demo, all SS on the maps are left untouched and will appear as mapthings without sprites.

3) Access to map33 (again, in single-player mode) will not be restricted to the IWAD being DOOM2.WAD from the BFG Edition, because there are already PWADs like D2TWID out there which feature a map33 and a secret exit on map02 and it should be able to progress the maps as intended even with Vanilla's DOOM2.WAD as the underlying IWAD.

**Comment by plumsinus** [comment]
>Access to map33 from the secret exit in map02 is only available in single-player games, not in network games or while recording or playing back a demo. 

Ah, I didn't remember this being the case. Is this true even if using doom2bfg.wad?

**Comment by fabiangreffrath** [comment]
> Is this true even if using doom2bfg.wad?

Yes. Rationale: It is impossible anyway to record demos or play network games with the original executable of the BFG Edition, i.e. the part of the Doom 3 BFG Edition start screen that starts "Classic Doom". Thus, the only way to record demos or play network games with these IWADs is DOOM2.EXE (or a source port). And thus, Crispy behaves like DOOM2.EXE in these cases even if it detects the BFG Edition IWADs.

**Comment by Danfun64** [comment]
I played map33 of D2TWID with solo-net. It warps to map01. I thought vanilla behavior would be to look for a map34 and, since it doesn't exist in D2TWID, crash.

**Comment by fabiangreffrath** [comment]
> Is vanilla behavior looking for a map34 and, since it doesn't exist in D2TWID, crashing?

Honestly, I don't know. But since crashing is the worst thing that could happen, I am not going to emulate this behavior. ;)

**Comment by fabiangreffrath** [comment]
Can this get closed now or is there anything else that needs to get discussed here?

**Comment by Danfun64** [comment]
Sorry. Didn't notice.
