### ISSUE TITLE
Implement SMMU's swirling flats

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/crispy-doom#93]
This replaces a series of animated flats with a swirling animation of only the first flat of the series. Which is also where its problems lie: It looks neat but would require special-casing for PWADs that contain animated flats series that have one or more or their flats replaced for special effects. These effects would simply not be visible. Still not sure if it's worth it?

**Comment by plumsinus** [comment]
Swirling flats would be cool, might be easiest just to have an on/off option and people who use it would disable it as needed. Some pwads replace animated flats with ones that would work fine when swirled, some would look bad, and I can't imagine a good way of differentiating between the two.

Would you respect the SMMU extensions to Boom's ANIMATED lump? (If the delay between flat frames > 65535, swirl instead of animating.)

**Comment by fabiangreffrath** [comment]
> [...] and I can't imagine a good way of differentiating between the two.

Me too. And as you might know, I am all against adding another switch to turn this on/off globally. ;)

> Would you respect SMMU extensions to Boom's ANIMATED lump? 

Yes, of course.

**Comment by plumsinus** [comment]
>And as you might know, I am all against adding another switch to turn this on/off globally. ;)

No surprise there. However I think unconditionally swirling even the regular Doom flats is a pretty big change visually, and you should expect a lot of complaints on Doomworld if you do it :p

**Comment by fabiangreffrath** [comment]
Having thought about it, swirling flats do simply replace one animation (the one chosen by the original artist) by another one (swirling of the first flat), which sometimes looks quite well and sometimes looks like shit. I considered the options suggested in your previous reply (i.e. enabling the swirling animation from ANIMATED lumps), but is this feature really that popular? Are there any MegaWADs out there that explicitly enable the swirling animation for some flats by means of an ANIMATED lump?

**Comment by plumsinus** [comment]
>Are there any MegaWADs out there that explicitly enable the swirling animation for some flats by means of an ANIMATED lump?

Maybe but I don't know of any off-hand. And limit-removing wads that use this feature are probably especially rare.

**Comment by fabiangreffrath** [comment]
So this is very, very low on the priority list. ;)

**Comment by plumsinus** [comment]
What I was secretly hoping for when you posted this, is that you would add swirling to Crispy Doom *and* submit a patch for PrBoom+ so that future limit-removing (or Boom) maps could implement water swirling for liquid textures and it would be supported across multiple ports. That's if entryway even wants that feature in PrB+ of course...

**Comment by fabiangreffrath** [comment]
Maybe I will do this, both of it. ;)
