### ISSUE TITLE
[Bug] Command Line Not Functioning As Expected

### ISSUE THREAD

**Issue by icedmacchiato14** [fabiangreffrath/crispy-doom#930]
Version of Crispy Doom:
5.11.1

Operating System and version:
Windows 10 Home - 21H2

Game: (Doom/Heretic/Hexen/Strife/other)
Doom 2, Final Doom, and Doom 1, etc...

### Bug description
I want to have separate saves and configs for each doom game I run through crispy, I am using Doom Launcher to manage instances and do command line options.
Running command line options, neither are functioning as expected.
-savedir "save\doom2" -config "doom2.cfg"

Observed behavior:
-When attempting to save in game, it says "Failed to open savegame file 'save\doom2\temp.dsg' for writing"
-The game generates doom2.cfg as expected but unexpectedly loads crispy-doom.cfg anyways.

Expected behavior:
-Savegame to save in folder I requested
-Separate functional custom config seperate from crispy-doom.cfg

**Comment by mikeday0** [comment]
Regarding the config file, Crispy Doom actually has two. If you want to specify custom locations for each, you need use both the `-config <file>` and `-extraconfig <file>` command-line options.

I can repeat your `-savedir <dir1>/<dir2>` issue. It happens when `<dir1>` does not yet exist. As a workaround, created the `<dir1>` manually first. This bug is also present in Chocolate Doom (which Crispy inherits from), so I recommend opening an issue there.

**Comment by icedmacchiato14** [comment]
> Regarding the config file, Crispy Doom actually has two. If you want to specify custom locations for each, you need use both the `-config <file>` and `-extraconfig <file>` command-line options.
> 
> I can repeat your `-savedir <dir1>/<dir2>` issue. It happens when `<dir1>` does not yet exist. As a workaround, created the `<dir1>` manually first. This bug is also present in Chocolate Doom (which Crispy inherits from), so I recommend opening an issue there.

Awesome thank you, I gave it a try
