### ISSUE TITLE
cripsy-doom overwrites chocolate-doom man pages.

### ISSUE THREAD

**Issue by benalb** [fabiangreffrath/crispy-doom#936]
### Background

Version of Crispy Doom:
Crispy Doom 5.12.0

Operating System and version:
Void Linux

### Bug description
Chocolate Doom and Crispy Doom share the default.cfg, hexen.cfg and heretic.cfg man pages:

/usr/share/man/man5/default.cfg.5
/usr/share/man/man5/heretic.cfg.5
/usr/share/man/man5/hexen.cfg.5

and they are overwritten upon installation. 

Observed behavior:
If chocolate-doom is installed on the system, the man pages are overwritten.

Expected behavior:
Avoid overwriting, changing them to something like cripsy-default.cfg.

**Comment by fabiangreffrath** [comment]
Yes, the manpages are called like that because that's how the files that are documented are called. Indeed, for the Debian package I have to rename the manpages out of the way to avoid the namespace clash with Chocolate Doom:

https://salsa.debian.org/debian/crispy-doom/-/blob/master/debian/rules#L17

**Comment by benalb** [comment]
Ok, thank you very much, will follow that route packaging crispy-doom for Void Linux. 
Closing the issue.
