### ISSUE TITLE
Preserve IDMUS music change across save/load (at least without quitting)

### ISSUE THREAD

**Issue by plumsinus** [fabiangreffrath/crispy-doom#94]
Would it be possible to store the music selection made with IDMUS as some sort of temporary variable, so that saving and then loading does not reset the music, as long as the player hasn't quit the program? Music selection can be cleared on new level (or any music change other than reloading), or when exiting the game.

**Comment by fabiangreffrath** [comment]
Sounds interesting. What should happen if you are on MAP01, use IDMUS to change music to e.g. that of MAP02 and then load a game saved on MAP03? Should the music of MAP03 play, because that the natural choice for that map, of should the music of MAP02 play, because that's you one you have explicitly chosen?

**Comment by plumsinus** [comment]
I would say MAP03, since that's a natural music change.

**Comment by fabiangreffrath** [comment]
So this condenses into "do not change the music if re-loading the same map again"?

**Comment by fabiangreffrath** [comment]
An example, just to make sure I get this right:

IDCLEV01
In map 01, plays map 01 music
IDMUS02
In map 01, plays map 02 music
IDCLEV03
In map 03, plays map 03 music
IDCLEV01
Back to map 01, plays map 01 music

Is this right, or should it play map 02 music on map 01 when returning from map 03?

**Comment by plumsinus** [comment]
>An example, just to make sure I get this right:

That is right! Thanks.
