### ISSUE TITLE
[Suggestion] Sound boost, quieter music, or sound/music normalization

### ISSUE THREAD

**Issue by hfc2x** [fabiangreffrath/crispy-doom#951]
Hello there. I was just wondering if Heretic could have a SFX boost option, because vanilla Heretic is known for having really quiet sound effects, coupled with really loud music. Even setting the music volume to 1 and maxing out the SFX is barely enough to make them even.

**Comment by hfc2x** [comment]
I'm currently on Linux, and using FluidSynth for MIDI. But this makes no real difference considering even when played on DOS Heretic has really quiet sounds and loud music compared to all other Doom engine games.

**Comment by mikeday0** [comment]
I just checked Fluidsynth on Linux with a SC-55 soundfont and do not see this issue. The balance seems good for me with SFX at 8 and music at 3. What soundfont are you using?

BTW, unlike Doom the SC-55 was not the target playback device for Heretic music. It was apparently some flavor of OPL. See [here](https://www.doomworld.com/forum/post/1927601). I've noticed that the instrument balance is quite poor (drums and strings are way too loud) for Heretic tracks when using SC-55 flavored soundfonts. I mention it just in case this might be contributing to your issue as well.

**Comment by hfc2x** [comment]
I'm using an SC-55 soundfont as well currently, and I've tried with an emulated Windows General MIDI soundfount as well, but it's the same. However, this problem has existed since forever. Even back in the day when I discovered Heretic, and I played it on Windows 98 with Windows GM, it always bothered me that the music was just really loud and the game sounds were barely audible, which didn't happen in any other game, not even HeXen.

> BTW, unlike Doom the SC-55 was not the target playback device for Heretic music. It was apparently some flavor of OPL. See [here](https://www.doomworld.com/forum/post/1927601).

This is really interesting, actually. Setting the music to OPL3 (which seems like the proper sound emulation for the intended sound) makes the music quiet enough so that it plays at a reasonable volume in comparison to the rest of the sound effects. It's probably the reason why the overall sound and music design were balanced this way originally. However, it doesn't change the fact that the game is MIDI-compatible, and if the user selects this option, the in-game sounds really could use a boost because of the lack of balance. Of course, this could all be optional, since the goal is to keep things vanilla-compatible.

**Comment by ceski-1** [comment]
@hfc2x
The AWE32 had two synths, EMU8000 and OPL3, so there's a theory the music was written with the EMU8000 in mind. For true General MIDI support, the AWE32 would load SYNTHGM.SBK or SYNTHGS.SBK into memory, for GM or GS support.

Anyway, give one of [these soundfonts](https://github.com/fabiangreffrath/crispy-doom/files/9602782/1MGM.zip) a try. They play the infamous E2M3 guitar correctly and the E1M9 horns are there at 10s and 26s. Compared to a real AWE32, FluidSynth with one of these soundfonts is pretty close but without the heavy reverb. The volume seems fine to me.

**1MGM.SF2** - Identical to the original AWE32/AWE64 ROM
**1MGM_GM.SF2** - 1MGM.SF2 merged with SYNTHGM.SBK for GM support
**1MGM_GS.SF2** - 1MGM.SF2 merged with SYNTHGS.SBK for GS support
**1MGM_xfi.SF2** - Unknown changes, originally included with Sound Blaster X-Fi drivers

**Comment by rzhxiii** [comment]
@ceski-1 sorry for derailing a bit, but which one of the four listed would you personally recommend? Also, are there any settings (reverb, chorus, balancing) for VirtualMIDISynth that you would recommend?

**Comment by mikeday0** [comment]
Thanks @ceski-1! I had never heard the Heretic soundtrack played on the AWE32 via the EMU8000. Is [this](https://www.youtube.com/playlist?list=PLr88YJ3aDghtnJ2LW_wP1qAjf-JzVCDUx) accurate? I am somewhat of a OPL purist for Heretic/Hexen but I have to admit that this sounds really good. I could definitely believe this was Kevin Schindler's intended playback device.

**Comment by ceski-1** [comment]
> @ceski-1 sorry for derailing a bit, but which one of the four listed would you personally recommend? Also, are there any settings (reverb, chorus, balancing) for VirtualMIDISynth that you would recommend?

Probably 1MGM.SF2 or 1MGM_GM.SF2 for the original Heretic/Hexen music.

Why? Well, earlier I mentioned that the AWE32 would load external compatibility soundbanks for GM or GS support because "out of the box" the AWE32 didn't technically support General MIDI. But this workaround couldn't be used by "protected mode" DOS programs such as the Doom engine games (a good explanation is at the bottom of [this page](https://retronn.de/imports/soundblaster_config_guide.html)). So to support the AWE32, the Doom engine games had a separate driver to do any necessary adjustments itself:

![setup](https://user-images.githubusercontent.com/56656010/191324980-efacf279-6ad2-40ce-8bcc-914854700647.png)

It's too bad we don't have access to the music system (DMX) source code to see the exact details. Now let's fast forward to the present and look at the source ports:
1. Nothing emulates the AWE32 and when we use soundfonts, General MIDI or Roland GS support is implied.
2. The original Doom engine music was only GM1, so GS support isn't needed (custom wads are a different story!).

So again, my best guess is **use 1MGM.SF2 or 1MGM_GM.SF2 for the original Heretic/Hexen music**. See below for the other settings.

> Thanks @ceski-1! I had never heard the Heretic soundtrack played on the AWE32 via the EMU8000. Is [this](https://www.youtube.com/playlist?list=PLr88YJ3aDghtnJ2LW_wP1qAjf-JzVCDUx) accurate? I am somewhat of a OPL purist for Heretic/Hexen but I have to admit that this sounds really good. I could definitely believe this was Kevin Schilder's intended playback device.

Yeah that sounds right. [This](https://www.wavetable.nl/heretic/) is a good reference too but it's only E1M1 and E1M2. Notice the unique sound profile that has a lot of reverb? No amount of tweaking with FluidSynth or VirtualMIDISynth really matches it (FluidSynth in particular has really poor reverb/chorus, so I'm not surprised that a lot of source ports disable it). My guess is that, similar to the SC-55, the AWE32 did some processing that's not emulated yet so soundfonts alone can only take us so far.

With that in mind, to get close to sounding like the AWE32, increase the reverb as much as you prefer and make sure the reverb and chorus "types" are the default ones:

Reverb Type: Hall 2 (aka Large Hall)
Chorus Type: Chorus 3

**Comment by hfc2x** [comment]
> Anyway, give one of [these soundfonts](https://github.com/fabiangreffrath/crispy-doom/files/9602782/1MGM.zip) a try. They play the infamous E2M3 guitar correctly and the E1M9 horns are there at 10s and 26s. Compared to a real AWE32, FluidSynth with one of these soundfonts is pretty close but without the heavy reverb. The volume seems fine to me.

None of these solve the volume problem for me. I still have to set the music volume to at most 3 and sounds to 15 to even be able to hear anything in game other than the music. HeXen on the other hand, sounds fine with music at 7 and sounds at 15 if I use a MIDI soundfont. The volume in Heretic only sounds proper with OPL.

**Comment by mikeday0** [comment]
One more thing to try. Open up your `crispy-heretic.cfg` file and check the `use_libsamplerate` config variable. If it's set to 1 (meaning Crispy Heretic is using the libsamplerate linear interpolation filter for resampling) then set the `libsamplerate_scale` variable right below it to 1.0.

**Comment by hfc2x** [comment]
Ah, okay. That'd be the workaround that does it then. I'll close this now.

Unrelated to this (although still related to my issues with the game), I know I made a PWAD for Heretic years ago where I boosted the majority of the sounds in the game because it bothered me how quiet everything but the weapons is in the game. It was in my old Win98 computer, but I tried to boot it up just now and the PSU exploded, so no PWAD for me lol. Time to replace it I suppose.

**Comment by ceski-1** [comment]
> [...] The original Doom engine music was only GM1, so GS support isn't needed [...]

I know this is a closed issue, but I should correct myself here. There are some Doom/Heretic/Hexen songs that use GS instruments. Doom and Heretic do a GM System On when launched. By the time Hexen was released someone must have noticed this because it's the only one that performs a GS Reset.
