### ISSUE TITLE
Crushed baron/hell knight corpses aren't entirely green

### ISSUE THREAD

**Issue by plumsinus** [fabiangreffrath/crispy-doom#97]
They get a different sprite than just the blood pool, and I guess it has some colours in the 16-47 red range.

![doom24](https://cloud.githubusercontent.com/assets/5642091/13770163/86e5f142-ea5b-11e5-83ea-1b2fab4a4fa6.png)

**Comment by fabiangreffrath** [comment]
Well, that's *on purpose*. I re-introduced the original GREEN and BLUE2 colormaps from Boom *because* they leave some colors intact. I wasn't satisfied with the looks of the gore pools when tranformed with Crispy's all-green and all-blue colormaps. They turned out as dull green and blue piles and didn't really look like crushed corpses. 

I like it much better this way. If you want I can provide some before/after images?

**Comment by fabiangreffrath** [comment]
For comparison:

![doom00](https://cloud.githubusercontent.com/assets/6449237/13794552/c00aa480-eafc-11e5-9c46-a735b6c0eedd.png)

![doom01](https://cloud.githubusercontent.com/assets/6449237/13794559/c67ccec4-eafc-11e5-910c-d1cd8676337f.png)

**Comment by plumsinus** [comment]
OK, sure.
