### ISSUE TITLE
No noticeable pixel smoothing effect with default max value

### ISSUE THREAD

**Issue by pyreck** [fabiangreffrath/crispy-doom#989]
### Background

Version of Crispy Doom:
crispy-doom-5.12.0-win32

Operating System and version:
Microsoft Windows 10 Pro Version	10.0.19044 Build 19044

Game: Doom

Any loaded WADs and mods (please include full command line):  No WADS loaded or arguments passed, just running the .exe with any IWAD

### Bug description

Observed behavior: When pixel smoothing is set to on (by default), there is no noticeable smoothing effect when config variable max_scaling_buffer_pixels is set to its default value of  = 16000000

Expected behavior: When I change the max_scaling_buffer_pixels to it's minimum value 256600, there is a noticeable smoothing effect (the gibbed corpse in particular). As a suggestion, should the value default somewhere on the lower range between (256600 - 16000000). Thanks

No smoothing:
![NO_SMOOTH_SCALE](https://user-images.githubusercontent.com/121589683/210443858-d661e5f1-13aa-43c7-94f5-f92ecdb26563.png)

Smoothing (max_scaling_buffer_pixels = 16000000):
![SMOOTH_SCALE_16000000](https://user-images.githubusercontent.com/121589683/210444526-2daf2e79-b300-4926-91af-9d199e61bbbd.png)

Smoothing (max_scaling_buffer_pixels = 256600):
![SMOOTH_SCALE_256600](https://user-images.githubusercontent.com/121589683/210445017-bdefba86-44a7-47b8-8b34-8dda938d30d1.png)

**Comment by fabiangreffrath** [comment]
> No smoothing:
> [...]
> Smoothing (max_scaling_buffer_pixels = 16000000):

Well, there *is* a subtle difference between both pictures and you can see it if you open both in separate browser tabs and switch between them. You will notice that on the second image, sharp contrast look indeed smoother, e.g. the pile of gore in the middle.

> Smoothing (max_scaling_buffer_pixels = 256600):

Nope, what you have done here is to artificially reduce the resolution of the intermediate texture that is used to *upscale* the framebuffer, in order to *downscale* its content into the game window. What you have applied here is "blurring".
